### ISSUE TITLE
Database optimizer should show storage gained

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1126]
After the running the database optimizer tool it should show you how much storage space you gained and not how many databases it touched. Second you should add sort options for sorting after database size and database size reduction/increase.

**Comment by d4rken** [comment]
> After the running the database optimizer tool it should show you how much storage space you gained and not how many databases it touched.

How do you imagine this would be displayed?

>  Second you should add sort options for sorting after database size and database size reduction/increase.

One feature/issue per ticket please.

**Comment by SuperSandro2000** [comment]
> How do you imagine this would be displayed?
In the quick acces tab like all other tabs. For example: "20 MB gained" or "2016 Databases touched and 20 MB gained."
> One feature/issue per ticket please.
opened another one. #1136

**Comment by d4rken** [comment]
> In the quick acces tab like all other tabs. For example: "20 MB gained" or "2016 Databases touched and 20 MB gained."

Hm, I think I had something like this in SD Maid v2 or v3? If I remember correctly, the issue is that people were confused which lead to lots of mails and or bad ratings.

* People would say that the tool isn't working because it showed 0KB gained. They expected the tool to regularly free large amounts of space, but as this is totally dependend on what the other apps do with their database, this is out of SD Maids control.
* There were also negative ratings because SD Maid displayed a negative amount of space gained. This can happen if apps access their databases between SD Maid's size measurements or in some cases when executing VACUUM on an empty database.

While I'm generally fond of displaying everything as accurately as possible, I was quite annoyed by having to explain these results regularly... I'm not sure what to do about this.

**Comment by SuperSandro2000** [comment]
I'm not sure either because I fully understand your concern

**Comment by d4rken** [comment]
I would guess there is a large overlap between people that don't understand the results, and those that never leave the QuickAccess page.

I could possibly keep the QuickAccess page results as is, and make the Databases page itself more detailed...

I'll do a larger rework of the tool with #1089 and #1067, maybe as part of that?

We'll only know how people react after releasing to production though, most people in beta testing are power users that understand the results. Releasing this to production, noticing negative feedback, making another update etc. ... ☹️

**Comment by SuperSandro2000** [comment]
> I could possibly keep the QuickAccess page results as is, and make the Databases page itself more detailed...

Making the Database page more detailed is a great Idea!
> I'll do a larger rework of the tool with #1089 and #1067, maybe as part of that?
Sure, go ahead. No rush changing this little thing.

**Comment by d4rken** [comment]
Adjusted the results message to show how much was gained in 8c7a409c64b15b29de53a2898c24a41dedec181f
