### ISSUE TITLE
Conflict System Cleaner and Exceptions

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1290]
Even having nothing to be clean is showing amount and size of files that need to be deleted erroneously. This error is happening because the files are protected in exceptions. Should not show these values, it should show 0 items.

Device: Asus Zenfone 2 Laser
Android: 6.0.1
Version SD Maid: 4.8.5

![screenshot_20171102-001424](https://user-images.githubusercontent.com/8754997/32306712-3a641788-bf64-11e7-8341-d801960c42ed.jpg)
![screenshot_20171102-001518](https://user-images.githubusercontent.com/8754997/32306710-39fd71cc-bf64-11e7-92d2-e58f3d75f958.jpg)
![screenshot_20171102-001427](https://user-images.githubusercontent.com/8754997/32306711-3a2bf132-bf64-11e7-917d-2f4b59203c1c.jpg)
![screenshot_20171102-001933](https://user-images.githubusercontent.com/8754997/32306709-39cedbc8-bf64-11e7-8926-484e9a7551a8.jpg)

**Comment by 21101969sanjay** [comment]
Not sporting mi max 2

**Comment by GabrielMGitHub** [comment]
@d4rken The version that presents this error is not the one of production, but of development. Version 4.8.5.

**Comment by d4rken** [comment]
Could confirm this. Nice catch @GabrielMGitHub .

**Comment by d4rken** [comment]
The issue was that there were two routines to update the scan results object, one that sets the final data and one that increases the size and file counter with every nice filtered file. Increasing the counters with every file was a remnant from an older routine to display progress information. The exclusions were still valid, it was the progress information that was buggy.

While the exclusion removed the files from the final dataset, this happened after the counters were already increased. I've fixed the overall code and removed the manual counters. When setting the filtered files to the `Scantask.Result` object, we can just count the items and size. So overall the code is cleaner 👍 

Fix commited for the next update.

**Comment by GabrielMGitHub** [comment]
@d4rken Thank you for your work and attention.

**Comment by d4rken** [comment]
I shouldn't have deleted your comment @21101969sanjay, I thought it was spam, sorry.
