### ISSUE TITLE
Application hang while managing duplicates

### ISSUE THREAD

**Issue by LinkSoraZelda** [d4rken/sdmaid-public#1306]
About a few hundred thousand dupes found, on a 200gb microSD. After left for over an hour the application doesn't delete anything and is still hung on the selection bullet list with no progress afterwards

S7 edge; Android 7.0; SanDisk Ultra 200gb microSD; default SD Maid settings
https://youtu.be/CdAdp84H77c
Maid PRO v4.8.3

**Comment by LinkSoraZelda** [comment]
There's a few thousand dupes found on a 200gb microSD, will edit original post soon

**Comment by d4rken** [comment]
Yeah it's the list selection process, the issue is that it happens on the UI thread which causes the hang.

Dub of #842.

The video is good, thanks!

For now I would recommend to exclude the game files visible in the video, those are likely "wanted" duplicates, but none the less, SD Maid should not hang :(.
