### ISSUE TITLE
SD Maid conflict LP

### ISSUE THREAD

**Issue by RE3CON** [d4rken/sdmaid-public#1454]
SD Maid and LP conflict to cleaning up to much from LP folders!
Make sure the Folder /storage/-device Name id-/Android/data/com.android.vending.billing.InAppBillingService.COIN/files/LuckyPatcher
get never deleted or LP fails to work and needs to be reinstalled !
General exclusion NOT user "exclude filter" to exclude the data/com.android.vending.billing.InAppBillingService.COIN/ and all content in this folder with subfolders.
An internal fixed in code white listing inside SD Maid to exclude touching this folder with subs.

To many "just download and install" users, users who duno English, French, Spain, German or even Russian or any other "Main Language", entire communites, loz of forums have LP installed and the user alone doesn't read how todo mighty be not find the right folder which needs to be exclude!
It cause an never ending cycle of reinstalling LP, the one or other find out that it always happens when SD Maid was cleaning.

**Comment by d4rken** [comment]
The conflict exists because LuckyPatcher changes it's packagename regularly to evade detection for obvious reasons.

This means that any path `com.android.vending.billing.InAppBillingService.COIN` is only valid until the package changes the next time making it infeasible to create default exclusions for this, while some regex magic could be applied here, nothing prevents the dev from completely changing the packagename the next time. A too broad matching pair would also mean that SD Maid can no longer detect corpses from old LP installs or even incorrectly matches with other apps.

I'm all about making SD Maid the most thorough and accurate tool, so if there is a false positive match I'm interested in fixing it, but I'm not looking to create special work arounds that make SD Maid less thorough just to make it easier for people to pirate apps.

The only clean solution I currently see is to just create a report whenever LuckyPatcher changes the packagename again.


The current database might contain some mismatches we could clean up.

I just did a quick lookup and saw a matching pair with
```
pkg=com.android.vending.billing.InAppBillingService.LACK
PUBLIC_DATA dir=com.android.vending.billing.InAppBillingService.LUCK
```

Kinda looks like `LACK` and `LUCK` should be the same, is this an error in SD Maids database or just the way it is?

You reported `Android/data/com.android.vending.billing.InAppBillingService.COIN`, what's the packagename of the installed app?

**Comment by d4rken** [comment]
Lack of info to fix this.
