### ISSUE TITLE
Task manager features

### ISSUE THREAD

**Issue by Tuxi** [d4rken/sdmaid-public#1691]
this software completely meets system maintenance. only lack: the ability to manage processes like greenify.

**Comment by d4rken** [comment]
Please expand on what functionality you are missing and what your use-cases are and how it would be a good fit for SD Maid.

**Comment by d4rken** [comment]
There is an experimental feature already in the pipeline for v4.11.0 that allows you to place a widget for each app that acts like a shortcut to AppControls "freeze app".

The idea is that when you press it the first time, the app the enabled and opened, and if you press it again, the app is disabled.

**Comment by Tuxi** [comment]
I was not referring to the freezing function. if I do not understand correctly you intend to enable / disable an application. I was thinking of a taskmanager function by switching off background applications (like greenify). it would be perfect to have only one program that does all this instead of having 2/3 for each function.

**Comment by d4rken** [comment]
What does "switching off background applications" mean though? There is no specific Android feature like that. I'm not a Greenify user myself so I'm not sure how it works.

**Comment by potjanat** [comment]
d4rken / sdmaid-public
Code Issues 134 Pull requests 0 Projects 0 Pulse
Jump to bottom
Open
Task manager features #1691
@Tuxi
Tuxi opened this issue
11 days ago
c: AppControl enhancement needs info/repro

this software completely meets system maintenance. only lack: the ability to manage processes like greenify.
d4rken added the enhancement label
11 days ago
d4rken added the c: Core label
11 days ago
d4rken added the needs info/repro label
11 days ago
@d4rken
d4rken
commented 11 days ago

Please expand on what functionality you are missing and what your use-cases are and how it would be a good fit for SD Maid.
@Tuxi
Tuxi commented 10 days ago • edited 10 days ago

Fuctions that helps you in Hibernating Applications Installed in Your Phone..which leads to more Free RAM & More Standby Time.. Whenever you hibertate an app it just completely disable it like it is not Present in Your android.
d4rken removed the needs info/repro label
8 days ago
d4rken added the c: AppControl label
8 days ago
d4rken removed the c: Core label
8 days ago
d4rken added this to the v4.11.0 milestone
8 days ago
@d4rken
d4rken
commented 8 days ago

There is an experimental feature already in the pipeline for v4.11.0 that allows you to place a widget for each app that acts like a shortcut to AppControls "freeze app".

The idea is that when you press it the first time, the app the enabled and opened, and if you press it again, the app is disabled.
@Tuxi
Tuxi
commented 7 days ago

I was not referring to the freezing function. if I do not understand correctly you intend to enable / disable an application. I was thinking of a taskmanager function by switching off background applications (like greenify). it would be perfect to have only one program that does all this instead of having 2/3 for each function.
d4rken removed this from the v4.11.0 milestone
7 days ago
d4rken added this to the Next Tasks milestone
7 days ago
d4rken added the needs info/repro label
7 days ago
@d4rken
d4rken
commented 7 days ago

What does "switching off background applications" mean though? There is no specific Android feature like that. I'm not a Greenify user myself so I'm not sure how it works.
Comment on issue
Notifications for this thread

You’re not receiving notifications from this thread.

    Sign out

**Comment by d4rken** [comment]
I consider any "task manager" feature that requires monitoring processes or borders on "RAM cleaning" is out of scope for SD Maid.
