### ISSUE TITLE
Clutterreport: /storage/sdcard1/Android/data/com.delphicoder.flud (FP)

### ISSUE THREAD

**Issue by jug007** [d4rken/sdmaid-public#1820]
### Target
Target: `/storage/sdcard1/Android/data/com.delphicoder.flud`
Prefix-free: `com.delphicoder.flud`
Path-prefix: `/storage/sdcard1/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `Xiaomi/2014819/HM2014819:5.1.1/LMY47V/V9.2.5.0.LHJMIEK:user/release-keys`

### Comment
`This folder is used by flud to save downloaded files by default. `

**Comment by d4rken** [comment]
The owning app is currently not installed on your device, is that correct?
Otherwise the if the `id` is really `com.delphicoder.flud`  and the app is still installed, then SD Maid should have populated the owner field in this report.

I'm not sure if marking this as "keeper" is actually effective, theoretically the system itself should have removed this folder when the app was uninstalled, because the ID equals the folder name. Was the sdcard removed from your device when that happened?

**Comment by jug007** [comment]
Oh yeah I think I flashed a new rom onto the device because the original
wouldn't boot anymore after an update. So the app got removed from the
internal storage, while the data on the sdcard stayed on.
I just noticed that the path that is used to save the files is a "files"
folder inside the "com.delphicoder.flud" folder. Also it does not save
anything else on the sdcard as far as I know. According to their
description the reason they are doing this is because of permissions.
I am just thinking that someone might accidentally delete all of their old
downloads.

2018-07-05 10:45 GMT+02:00 Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment]
> According to their description the reason they are doing this is because of permissions.

Yeah because that path is "their own". If the files in this folder should stay behind the developer needs to put them somewhere else, though if they do that then we also have additional clutter that stays behind and would have to add that to SD Maid 😁 .

Android basically needs a system for apps to delcare optional directories and then the system could prompt the user on uninstall, maybe with a developer added description for each path.

> I am just thinking that someone might accidentally delete all of their old downloads.

I agree. I'm closing this ticket though because this is not false-positive match and marking this as "keeper" for SD Maid would be missleading because the system would remove it anyways on uninstall. In this case it just didn't happen due to a ROM flash.
