### ISSUE TITLE
Investigate ` /storage/emulated/0/waze/tts/database/Kathi/1531157432-731115-0.tts`

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1904]
Potential hidden cache.

```
 /storage/emulated/0/waze/tts/database/Kathi/1531157432-731115-0.tts
```

**Comment by gaya4** [comment]
Waze, online navigation app. This might be a voice file used for reading instructions to the user.
I don't currently have any voice there for some reason. Since I cleaned this directory several times already with other tools I suspect something else on my side. Will report if I notice something different.
