### ISSUE TITLE
Clutterreport: /storage/emulated/0/My Documents (new)

### ISSUE THREAD

**Issue by SimplyBrainy** [d4rken/sdmaid-public#1976]
### Target
Target: `/storage/emulated/0/My Documents`
Prefix-free: `My Documents`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Registratore vocale`
Packagename: `com.htc.soundrecorder`
Version: `9.00.999039 (954000100)`

### Current owners
None

### SD Maid
Version: `4.11.7 (41107)`

### Device
Fingerprint: `htc/ocndugl_00709/htc_ocndugl:8.0.0/OPR6.170623.013/1011554.7:user/release-keys`

**Comment by d4rken** [comment]
As per your other report the app owns the recordings subfolder here. We should only add that otherwise we'll get into issues where we could try to remove the parent directory `My Documents` even when there are other apps that own other folders inside of it.

So the report `com.htc.soundrecorder` <-> `My Documents/My Recordings` is good enough 👍 

In sometime I hope to write  an update that will make SD Maid better display and understand nested ownership relations like this.

**Comment by SimplyBrainy** [comment]
Thank you! It's a pleasure giving an help to improve such a beautiful mobile-tool! Waiting update!

Inviato da HTC U11

----- Rispondi al messaggio -----
Da: "Matthias Urhahn" <notifications@github.com>
A: "d4rken/sdmaid-public" <sdmaid-public@noreply.github.com>
Cc: "SimplyBrainy" <lorysan96@hotmail.it>, "Author" <author@noreply.github.com>
Oggetto: [d4rken/sdmaid-public] Clutterreport: /storage/emulated/0/My Documents (new) (#1976)
Data: mer, ago 29, 2018 13:18


As per your other report the app owns the recordings subfolder here. We should only add that otherwise we'll get into issues where we could try to remove the parent directory My Documents even when there are other apps that own other folders inside of it.

So the report com.htc.soundrecorder <-> My Documents/My Recordings is good enough 👍

In sometime I hope to write an update that will make SD Maid better display and understand nested ownership relations like this.
