### ISSUE TITLE
Migrate beta testing off of Google Plus

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2060]
With recent news of Google Plus being shut down in August 2019, it begs the question of what the next service that SD Maid will use for beta testing. Any ideas? Google Groups may work.

**Comment by IntenceYT** [comment]
Telegram might be a possibility.

**Comment by SuperSandro2000** [comment]
It is a very good one

**Comment by d4rken** [comment]
SD maid currently also has a subreddit:
https://www.reddit.com/r/sdmaid

And an XDA thread:
https://forum.xda-developers.com/showthread.php?t=1013063

**Comment by Fillabong** [comment]
TG has been my social media outlet for quite some time. G+ was antiquated imo, anyways.

**Comment by rodrigoswz** [comment]
Discord is awesome.

**Comment by SuperSandro2000** [comment]
Reddit could fit as well. I don't think XDA is a good choice as the community is "special".

Discord is for gamers mainly and not programmer

**Comment by najodleglejszy** [comment]
I'm not fond of Telegram or Discord, mostly because of their privacy practices (or rather lack of those). I think a subreddit is a good choice since you get organized (to a degree) threads, so that it helps to, say, get back to someone's issue fairly quickly instead of having a bug report or a reply buried in a Telegram chat.

**Comment by spider623** [comment]
I will give a vote to mewe.com it's closer to G+ than any other alternative and the team behind it is active, working right now to add more features to make it even more similar.

For just chat telegram it's fine

**Comment by MicaelJarniac** [comment]
Isn't this app using the Play Store feature for joining the beta program already? I'm pretty sure on the bottom of the app page there, there was a "Join beta" button, or something like that.

**Comment by najodleglejszy** [comment]
@MicaelJarniac it's about beta test-related discussion, which for now mostly goes on in the Google+ group, not a beta joining process.

**Comment by MicaelJarniac** [comment]
@najodleglejszy oh, got it. I thought it was the joining thing, because I've seen some other apps using G+ for that.

Well, with that in mind, I'd vote for Reddit. I mean, I'd guess anyone up to beta-testing an Android app has a Reddit account, and Reddit can be quite a nice and organized place, simple enough for people to not be scared of it, but still complete enough for some nice discussion.

I like the XDA Forums, but it's not very simple to use, and creating and managing an account there is a bit strange, at least for me. Also, I've used the XDA Forums for a few years now, and only last week have I created an account there. Sure, if this app was completely tied to a custom ROM, root, Xposed or that sort, having the beta discussion settled there would be nice, but I believe that's not the case.

I haven't used Telegram much, but for what I know, it's more focused on personal messaging than on large communities discussing about an app. I mean, I don't think it has the level of organization to suit our needs, like having separated topics with they'r own message chain, being able to tag submissions and so on.

Although I like Discord, as mentioned here it's mostly for gaming purposes, and the same thing I said for Telegram would apply here. Although it can have rooms inside of rooms that are inside of rooms (ok, not quite, but...), it still wouldn't suffice for long.

I've never heard of **mewe.com**, so I don't have an opinion.

Then there's also Gitter, which I think could work fine, but I haven't used it much. I believe it's focused on exactly this, the development of software, but I've used it very shortly.

So as I believe Reddit is simple, useful and a lot of people already has an account there, to name a few reasons, I'm on #TeamReddit. But if it happens to be the chosen one, I'd recommend creating another subreddit specific for the beta discussions, for that extra bit of organization.

**Comment by d4rken** [comment]
We'll replace G+ with Reddit: https://www.reddit.com/r/sdmaid/

I don't think Mewe is fitting because it advertises itself as "social network" and we don't really need a social network. We just need an easy way to talk about different topics (thread style), that requires as few personal infos as possible, while being accessible to many. For now reddit fits.
While Telegram is also nice "chat-style" communication isn't very useful to us.

Happy holidays :christmas_tree:

**Comment by d4rken** [comment]
As a compromise between Reddit and Telegram, Discord:

https://sdmaid.darken.eu/discord
