### ISSUE TITLE
scheduler activates activatemanager kill background

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2153]
I've installed a new rom (aosp) and I spent some days trying to figure out why viber wasn't working
(the day I set it up it was working, the next not),
until I found it yesterday, 
sdmaid's scheduler run at 09:46 (it was late too, I've set it up to run earlier) and
at the same time I noticed "activatemanager viber kill background"!!
does it use so many resources that forces android to kill background processes in order to free them up?

**Comment by d4rken** [comment]
Try enabling "Skip running" apps in the AppCleaner and Databases otherwise they might kill the app they are working on.

> does it use so many resources that forces android to kill background processes in order to free them up?

That's also possible.

**Comment by patrickdrd** [comment]
I've had "skip running" in databases, but not in appcleaner,
do you think it would be enough in order to not kill it?
or is the second?
what do you propose?
wait and see?

**Comment by d4rken** [comment]
> what do you propose?

> wait and see? 

:wink:

**Comment by patrickdrd** [comment]
ok, I'll tell you tomorrow if it was enough

**Comment by patrickdrd** [comment]
ok, I've simulated the situation and I've run it some minutes ago:
I switched on sd maid's scheduler to run in 3 minutes and turned on airplane mode and
it was killed again,
only solution is I use the "viber status icon", that way, even if "skip running" is unchecked in appcleaner, it isn't killed

**Comment by d4rken** [comment]
> only solution is I use the "viber status icon"

What's that?

**Comment by d4rken** [comment]
Oh, well it's not "under any circumstances", a visible notification just elevates it's priority. Things that are "invisible" to the user will be killed first. SD Maid displays a notification for similar reasons.

Viber is getting killed then because the system wants more memory. You can reduce SD Maids memory consumption by changing the process count to "1" in SD Maids advanced settings.

Nothing to be really done about this from SD Maids side.
