### ISSUE TITLE
Bug: Blank Explore Shortcut Icon

### ISSUE THREAD

**Issue by Johnny-Yh** [d4rken/sdmaid-public#2299]
### What happened?
In Android Pie.When I try to add a shortcut of the explorer to my launcher，the icon is blank

### What did you expect to happen?
Everytime when I try to add the shortcut

### How can I reproduce the issue?
Everytime when You try to add the shortcut

### SD Maid
Version: `4.13.1 (41301)`
Unlocker: ` (0) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys`

**Comment by d4rken** [comment]
Can you show me a screenshot?

**Comment by Johnny-Yh** [comment]
I just send you a mail.

**Comment by d4rken** [comment]
The icon is not blank, but it is white, so it's not visible because of the white background.

I will adjust the colors to make it visible!

Good report!
![screenshot_20190212-011927](https://user-images.githubusercontent.com/1439229/52582034-8701ed80-2e2c-11e9-8d09-026f52c3bfa2.png)
![screenshot_20190212-011935](https://user-images.githubusercontent.com/1439229/52582035-8701ed80-2e2c-11e9-88ab-f956c4c04181.png)

**Comment by d4rken** [comment]
![screenshot from 2019-02-20 17-41-19](https://user-images.githubusercontent.com/1439229/53108178-da63f200-3536-11e9-8f70-46b6a9f21341.png)
![screenshot from 2019-02-20 17-41-07](https://user-images.githubusercontent.com/1439229/53108179-da63f200-3536-11e9-9558-9daec4986ab9.png)


Hm still looking into whether I can use an adaptive icon here, so it looks a bit like the files app icon on your screen.

**Comment by d4rken** [comment]
![screenshot from 2019-02-21 01-22-30](https://user-images.githubusercontent.com/1439229/53134618-2daa6480-3578-11e9-8810-aa608c0ff44f.png)
