### ISSUE TITLE
Add IAPs as a payment method for SD Maid

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2414]
Ideal way to do this IMO is to keep the unlocker for existing users, and allow that to be updated. But allow existing users to have the unlocker so they can still update it and get the latest goodies. New users should only have the option of IAP or using apps darken.eu to make a purchase.
Device: Pixel XL
Android version: Stock 9 Pie with March 2019 updates
Root status: Rooted with Magisk 18.1
SD Maid version: Internal 4.14.0

**Comment by JavkhlanK** [comment]
I'd prefer the way with the GP, because you can't crack it without Root but you can crack the app without root (LuckyPatcher)

**Comment by d4rken** [comment]
From a security standpoint neither method is really more secure than the other. It will be cracked either way.

The biggest issue with adding IAPs as upgrade method is that it will confuse users. If i keep both methods, users are confused which to buy and if I remove the unlocker app, users are confused and will accuse me of scamming them because they don't understand how to reinstall the unlocker.

Both approaches have pros/cons. IAPs don't require an extra app, but don't work something like "family library". A paid unlocker app requires two apps, but works with "family library".

**Comment by JeffHorinzon** [comment]
I suggest constant client-server side key checking (kinda like "aggressive DRM") to ensure a legit copy is used.  If possible, link Gplay account purchased the pro key with a d4rken apps account and limit the number of devices installed on same key similar to Access Key style.
