### ISSUE TITLE
MSF Duplicates bad checksum?

### ISSUE THREAD

**Issue by fattieboombattie** [d4rken/sdmaid-public#2427]
Problems with duplicate being found in metasploit folder (msf) on ext4 external SD card. /sytem/emulated/0     /mnt/expand/67af517e-157e-4c0b-b155-34310a4ff5e0/ checksums seeing different file names as the same. Duplicate tool is the only place if ever had real issues with, such as, with TWRP folder, and dup's being found in video editing apps with vid effects. Tool sees files that are VERY close to the same size as same. Anyway of a more strict checksum?

**Comment by d4rken** [comment]
Please provide two samples of files that SD Maid says are the same but are actually not.
The final check is based on a MD5 checksum comparison and the chance for collisions is incredibly small.

Most false positives come from pathing issue, where the same storage is scanned twice, e.g. due to mounts being nested.

**Comment by d4rken** [comment]
stale
