### ISSUE TITLE
New permissions to view usage statistics?

### ISSUE THREAD

**Issue by Vstory** [d4rken/sdmaid-public#2444]
Version: 4.14.0, why does Sd Maid need this permission?
The previous version does not have this privilege and it works fine. Is this permission necessary?
There is no permission description here.
[Sd Maid wiki](https://github.com/d4rken/sdmaid-public/wiki/setup)

**Comment by d4rken** [comment]
> Version: 4.14.0, why does Sd Maid need this permission?

It should say that in the same screen where it asks for it? To determine app and cache sizes.

Since Android 8.0+ the reflection based method no longer works. Without it app sizes in AppControl are less accurate, and in AppCleaner you can't use "Show inaccessible" or "Accessibility Service".

Theoretically with root available it's not needed, but it makes things easier. But then the question is why not grant on rooted devices, as giving SD Maid root is a greater permission than usage stats.

What concerns you about this permission?

> There is no permission description here. Sd Maid wiki

Yeah need to update that, it's on the TODO list :)

**Comment by Vstory** [comment]
> What concerns you about this permission?

There is a question about whether this permission is necessary, but you have already answered it.

**Comment by d4rken** [comment]
I've updated the wiki documentation.
