### ISSUE TITLE
Error in layout when cleaning inaccessible applications

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2566]
These references marked in the image are active and when pressing the buttons the SD Maid pauses the cleaning then back alone, at the top you can download the quick access but only superimpose the cleaning screen, it would not be ideal to block the whole screen thus avoiding error  in the cleaning run of SD Maid?

![20190511_164214](https://user-images.githubusercontent.com/8754997/57574241-c7610f80-740b-11e9-8f89-1ca1925ad6c9.jpg)

**Comment by GabrielMGitHub** [comment]
When you download the Android block, SD Maid can not clear the application cache, it tries to clear the cache of the same application several times until it succeeds.

![20190512_031256](https://user-images.githubusercontent.com/8754997/57578580-66febc00-7465-11e9-807f-7e1d5392cd6d.jpg)

**Comment by d4rken** [comment]
The accessibility service (ACS) based deletion reads the screen, specifically the top most screen under the overlay. If you drag down the notification menu, SD Maid will no longer be able to read the window that she is looking for (`com.android.settings`) and retry until timeout, then abort.

Blocking the top and bottom layers is theoretically possible, but discouraged by Google (due to malicious apps abusing it) and will require more invasive permissions. Theoretically I could remove the whole overlay, but it's there to prevent accidental clicks while handling the device when SD Maid is doing this.

**Comment by GabrielMGitHub** [comment]
I think it should block the entire screen until cleaning is complete.

In the way that it works today a user can defame the application saying that it does not work correctly.

**Comment by d4rken** [comment]
> I think it should block the entire screen until cleaning is complete.

If I block the entire screen, the user can still turn the screen on/off or open the camera (double power button). An incoming call or other messages/popups can also interfere. It can't be made foolproof.

Users can always shoot themselves in the foot.  I think the current overlay is enough to make the user aware that interference will break it, which is all that we need. We could also make the overlay a lot smaller and just label it "hands off" :wink: .

> In the way that it works today a user can defame the application saying that it does not work correctly.

Users can always lie.

**Comment by GabrielMGitHub** [comment]
When I click on home, recent and back the SD Maid pauses for a few seconds and re-clean again, why not implement this when the user opens the Android block?
