### ISSUE TITLE
Q: what exactly is "SD Maid's naughty list ಠ_ಠ" ?

### ISSUE THREAD

**Issue by Younes-L** [d4rken/sdmaid-public#2597]

**Comment by d4rken** [comment]
A combination of SD Maids clutter database, which tells SD Maid what apps create non default folders, and  a database containing details about hidden caches.

e.g. we have an app called "Strawberry", that creates the folders:
* `/sdcard/.straw` and `/sdcard/berry` both remain on uninstall. Adding both to the clutter database will cause SD Maid to clean them up after uninstall
* While installed, there is also the folder `/sdcard/.straw/tempFiles/cacheFiles` which contains cache files, that the system will never clean due to being in a non-default path, adding this to SD Maid's hidden caches database will get it cleaned up too.

When there are apps like some from Tencent, that spam the sdcard with 4-5 different folders (e.g. `.UTSystemConfig`), then I jokingly talk about adding that app to the naughtly list (like :christmas_tree: 
 Santa Claus), which in reality are a couple internal databases :wink: .

**Comment by Younes-L** [comment]
Thank you for your time, nicely explained 👍
