### ISSUE TITLE
Multi select boot permissions

### ISSUE THREAD

**Issue by ShadyGaDa** [d4rken/sdmaid-public#2753]
If were possible to select more than one boot permission at a time and speed process up of en/dis able. An app search for particular permissions maybe.
Anyway still only app to catch them early hijackers. Thanks.

**Comment by d4rken** [comment]
This is potentially dangerous as users may carelessly just deactivate lots of receivers without understanding the consequences. This is my biggest concern with this.

I think people are already disabling stuff carelessly and this would make it even easier.

**Comment by ShadyGaDa** [comment]
You could have a 'Super advanced highly dangerous mode' and 'Warning! careful you don't completely disable your phone' Then a wait 30 secs re-enable button unless cancel is pressed.

**Comment by zQueal** [comment]
> This is potentially dangerous as users may carelessly just deactivate lots of receivers without understanding the consequences. This is my biggest concern with this.

Wouldn't this be a perfect feature for _experimental features_ under advanced settings? People clearly want it. I find it terribly inconvenient to remove `boot_completed` flags from processes I really don't think need it. Even if it's not the correct way to ensure that applications don't boot automatically on a restart, I'm probably going to do it anyways because I feel that it really does help. 🤷‍♂️ Being able to do it enmass would be a perfect boon for SDMaid, IMO.

Would really love it if you considered adding this feature.

**Comment by d4rken** [comment]
When hiding it behind safety flags, the amount of people that will use it is even less. We need to take care not to add too much code for too few people, so that maintenance becomes unnecessarily complex.

Specifically "batch selection" of app components, is a dangerous game. It does not do what most people think it does, and it does not work like most people think of it does.

I think that 99% of people that would use this, use it wrong. 

This ticket is even called `boot permissions`, but it's not about permissions, what we are doing is disabling  `BroadcastReceiver` that are registered for the `BOOT_COMPLETED` intent. 

Many think "Windows autostart", but it's nothing like that! This is not something that needs to be touched, muchless in batch mode for multiple apps. The whole feature exists to "tinker" with single apps.
Read:
https://github.com/d4rken/sdmaid-public/wiki/AppControl#receiver-manager-autostart

It was a mistake to introduce the `BOOT` highlight in the UI like this, as it sets the wrong expectations. It's difficult to remove now without upsetting users who don't understand how it works (#5231).

The only legit use-cases I see are out of scope for SD Maid and more fit for a special purpose app that targets specific BroadcastReceivers.
