### ISSUE TITLE
Startup Manager.... 

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#2892]
Good day,

**Startup Manager** 

Ability to stop apps from starting up when Android boots. The autostart feature (receiver manager) lists several entries, and some of them have "boot" mentioned against them. 

1. Will disabling them block apps from starting up on boot? 
2. Will that have any effect on the app functionality?

My device is rooted with Magisk. Can you make this process simpler by allowing us to simply select apps that must not start with Android boot? 

Also, it would be nice if it can work without root (using ADB commands or similar).

Thank you.

**Comment by d4rken** [comment]
> Will disabling them block apps from starting up on boot?

It will stop them from executing a routine during startup. It's not possible to "block" because the app itself can enable this receiver again (though not many do).

> Will that have any effect on the app functionality?

Yes, the routines launched by receivers are small pieces of code that may run for up to 10 seconds. Disabling this can break app functionality, but each app is different. A common use-case for on-boot receivers is restoring alarms/timers.

> My device is rooted with Magisk. Can you make this process simpler by allowing us to simply select apps that must not start with Android boot?

I don't want to make this too easy, i.e. a batch-all option, many users don't know what they are doing and will just break their apps without any benefit. If apps missbehave, disabling receivers is not very effective, it would be better to disable the whole app.

> Also, it would be nice if it can work without root (using ADB commands or similar).

This is possible without root, but only from a computer, not from the device itself.

**Comment by Sridhar-Ananthanarayanan** [comment]
The idea behind the request is to ensure that apps don't start automatically on boot. This is very helpful for users like me who use a firewall. 

The purpose of a firewall is to block/ control how apps access the network. The firewall app itself takes a while to start when booting Android. So if apps whose network connectivity is controlled by the firewall start before it, they can access the network until such time that the firewall starts, and that could be enough for them to collect logs and send them over the internet. 

So a way to either block them, or delay their behavior until the firewall starts would be helpful.
