### ISSUE TITLE
Set apps to system/user

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#29]
Originally reported by: **Bitbucket: [d4rken](http://bitbucket.org/d4rken), GitHub: [d4rken](http://github.com/d4rken)**

---

The AppControl feature could offer a button to make the selected app a system or user app.
Obviously requires root.

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/30

**Comment by Tajnymag** [comment]
So what is the conclusion? Are we there yet? :)

**Comment by d4rken** [comment]
Not yet, it's a viable feature, just wasn't high priority so far.

**Comment by huandney** [comment]
Yes, the only application I know who does this well is the Lucky Patcher, but does not give me to choose the destination folder. after a look because it will be an interesting function. if you need I'll help you : )

**Comment by d4rken** [comment]
@huandney If you know sites that talk about this in details, feel free to add further reading material for me here 😄

**Comment by rfgamaral** [comment]
Just showing my support for this feature...

I've been looking at a bunch of apps to do this and just thought to myself "I wonder of SD Maid can do this already?". Guess not, yet... :) Would really love to have this integrated instead of just using another [ugly] app just for this purpose. While SD Maid is great and gorgeous :D

**Comment by d4rken** [comment]
Closing this in favor of ticket #1342
