### ISSUE TITLE
CorpseFinder (update Clutter DB)

### ISSUE THREAD

**Issue by jpzex** [d4rken/sdmaid-public#299]
I have found some folders on my internal **SD Card** which belong to some apps and they re not added to the **CorpseFinder.** 

They are below:

Path | Owner |  Link  
------------ | ------------- | -------------
  */ProgramData* | Hide It Pro | [Link to Play Store](https://play.google.com/store/apps/details?id=com.hideitpro)
*/mcpemaster* | Master For Minecraft | [Link to Play Store](https://play.google.com/store/apps/details?id=com.groundhog.mcpemaster)
 */subtitles* | MX Player | [Link to Play Store](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad)

**Note:** The folder **/ProgramData** contains a kind of vault with photos/music/videos/notes the user created inside **Hide It Pro.** So, I think that folder might not be deleted by the **CorpseFinder.** I am just adding it here because it not on the *SD Maid Database*

**Comment by d4rken** [comment]
Uh, sorry. Took me a bit longer than I thought. All valid entries and they will be in the update.
I flagged them all as keeper though and ```ProgramData``` and ```subtitles``` due to their name as ```COMMON``` which means SD Maid knows these, but won't show them as corpses. They are still known though for other tools functionality.

Thanks :+1:
