### ISSUE TITLE
System cleaner settings are empty

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#315]
When I enter the system cleaner settings they are just empty and show nothing. I am on the latest beta and did a clean install a few days back. ROM Cm 13

**Comment by d4rken** [comment]
In v3 it only had one setting (e.g. "Enable CustomFilters") which is now on by default. We could either remove the settings or add something like "No settings". Just removing it could be a bit confusing because all other tools have settings.

Or we come up with a cool setting we can add so it isn't empty :grin:

**Comment by SuperSandro2000** [comment]
NJ UST add no settings.

**Comment by DO97** [comment]
Remove the setting if there isn't a setting.
