### ISSUE TITLE
"Apps" file manager for exclusions.

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#327]
Is it possible to put a file manager in exlusions that shows the installed apps (also system apps) for easier handling?

**Comment by Geocfu** [comment]
Lets say i want to exclude the nova launcher app but i dont know its location. With the "app" file manager i can just tap on it and done! Also eta for the new update?

**Comment by d4rken** [comment]
Knowing what pathes to exclude is not trivial though.
We can get the location of the default pathes from the system, such as ```/data/data/com.teslacoilsw.launcher```.  What if the app also has a folder ```/sdcard/NovaLauncher```? The system doesn't know about this and can't tell us. Some SD Maids tools such as SystemCleaner or Duplicates can still find that folder though.

So to be able to know these pathes we would have to run at least something like what AppControl does which involves trying to determine every possible folder an app could own.

Some tools who work on a "by app" basis, such as AppCleaner and Databases, could honor an exclude based on the packagename, but the other tools only know pathes, so if Nova Launcher owns 10 different pathes we would have know those and add 10 excludes.

Now what if we missed an 11th path and that gets picked up by any of the tools? The user would be under the impression that this is excluded too, but it isn't. Furthermore what if an app changes, the excludes are permanent, the folders an app owns are not (which is why the tools don't cache and have to refresh everytime)...

The only good way is add an exclusion based on a result from a tool (the current way).

Can you follow me concerns? :)

Update is basically ready, my tooling currently has an issue for which i might wait (https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/8)

**Comment by Geocfu** [comment]
> The only good way is add an exclusion based on a result from a tool (the current way).
Please explain.

What if we update the paths every time we make a pass. What i mean is adding tool to update exclusion paths or update the exclusion paths with some other tool(like we update the paths while we clean the apps cache etc.). This tool (tool to update exclusion paths) would only be activated if there is an exlusion request available. The tool would follow the "Apps" file manager conditions from the exclusions tool and update the paths.

**Comment by d4rken** [comment]
> What i mean is adding tool to update exclusion paths or update the exclusion paths with some other tool(like we update the paths while we clean the apps cache etc.).

The AppCleaner doesn't update any exclusions, but because all results are based on an app we can exclude app that matches a packagename.

Sure what you describe is possible, but it's all to complex and unclean, too big a source of agony, for too little gain. I don't like it. 

A better solution would be to teach tools (Corpse/System/Duplicates) to honor exclusions based on packagenames. I have already written tools to do that, e.g. the Explorer looks up every file to display the icons on the right. The caveat here is a huge slow down in speed. Possibly something that only happens if there is an exclusion for an app... But then we should introduce a specific app exclusion type and deprecate the old approach, not sure how we could migrate old exclusions from users though....

**Comment by d4rken** [comment]
So for an app list to help when making exclusions, we would first need make sure all tools can honor packagename based exclusions. This is even more difficult because we also have to deal with exclusions that target apps that are currently not even installed...

This is not going to happen, sorry. Cool idea though.
