### ISSUE TITLE
Is it possible to find out which application the folder belongs to?

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3400]
Есть ли стандартные способы определить, к какому приложению принадлежит папка, если это не смог определить SD maid?

**Comment by d4rken** [comment]
There is no special technique for this, it's usually recognizable by folder name or by the files inside the folder.

If it's not obvious you can sometimes just google the path and someone else in a forum might have already complained about app X creating folder Y :grin:.

For `Android/data` it's usually related to the package name, and doesn't always need a database entry because SD Maid will try to match a few common variations, but for the root of the sdcard (`/storage/emulated/0/...`) it requires some human intuition. :wink:

**Comment by d4rken** [comment]
I have looked into automating this by ways of machine learning or install monitoring, but in either case the data would not have been reliable enough to not require a human to look at it.
