### ISSUE TITLE
AppControl status has extra background

### ISSUE THREAD

**Issue by TWiStErRob** [d4rken/sdmaid-public#348]
The TextView(s) in the right column has a black (#212121) background, on the list's black (#303030) background:
![image](https://cloud.githubusercontent.com/assets/2906988/14244385/275483d2-fa5b-11e5-89f9-c70b3006cdff.png)
Not sure if that's intentional, it's more visible with higher brightness.

**Comment by d4rken** [comment]
Hey, thanks for your feedback :+1: .
It was intentional though have to admit that after I saw it on different display I was not happy with it anymore.
This is SD Maid v3.X and SD Maid v4.X is currently in rollout on Google Play.
v4 has a new UI where this no longer applies.

You can skip Googles Staged Rollout and grab the APK here:
http://sdmaid.darken.eu/download/production/
