### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3481]
### Target
Target: `/storage/emulated/0/Photo Editor`
Prefix-free: `Photo Editor`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by programmist87** [comment]
Почему папка помечена как небезопасная для удаления? Из-за того что другие приложения могут поместить в неё свои данные?

**Comment by d4rken** [comment]
Same reason as here, `Photo Editor` is a too common name, we can use the information for cache deletion, but not for corpse removal. So the entry is protected by the `common` flag in the database.

```
 {
  "pkgs": ["photo.editor.photoeditor.photoeditorpro"],
  "mrks": [{"loc": "SDCARD", "path": "Photo Editor", "flags": ["keeper", "common"]}]
}
```

**Comment by programmist87** [comment]
Получается другое приложение может создать точно такую же папку в той же директории?

**Comment by d4rken** [comment]
Yes.

"Photo Editor" is a very common name.

I think there are many other apps that might create a folder with such a common name.

If SD Maid doesn't know the other apps, then SD Maid would falsely suggest the folder for deletion.

So in this case it's too dangerous because folder name is too common, to protect against this, it's flagged as `common`. This way it will not cause false positive corpsefinder results, but AppCleaner will still check for caches.
