### ISSUE TITLE
Consistently makes Google photos crash

### ISSUE THREAD

**Issue by joseste4** [d4rken/sdmaid-public#360]
After the scan is complete and everything is deleting/optimizing there are always 2 failures in database. I'm not sure what they are but after all the processes are done Google Photos will always crash upon launch. 

ZenFone 2 (ZE551ML)
4GB ROM - Intel chipset
Rooted stock Rom

**Comment by d4rken** [comment]
SD Maid v4.1.4+ shows which databases failed.
E.g. VACUUM on the contacts database usually fails, this is not harmful though.

There were previously issues in <4.1.3 with the databases tool causing problems with the Google Photos app.

Please check what tool causes this issue and which version of SD Maid you have.

**Comment by joseste4** [comment]
I was on 4.1.3. I'm updating now and will try again. Thank you.

**Comment by joseste4** [comment]
I am now on 4.1.4 and Google photos is working again thank you very much. I'm sorry I missed the update. 

I had 3 failures  and 1 skip this time around. 

Contacts2.db
Profile.db
TVchat.db ( TeamViewer) 

Everything seems to be working fine. Thank you

**Comment by joseste4** [comment]
Ran SD Maid a 3rd time and this time around it was 153 skipped and 3 failed.

**Comment by d4rken** [comment]
The failed entries are likely due to additional table constrants sdmaids sql binary was not build for. It's not an issue. If you do a debug run log, you can search for "VACUUM failed" and read the error messages.

SD Maids skips databases of all running apps, you can turn it off in the settings. Apps may crash if they try to use their database while SD Maid works on it.

**Comment by joseste4** [comment]
Thank you for explaining it to me. Everything is working great again.
