### ISSUE TITLE
KingoUser hidden cache

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#381]
Looking for some pathdumps (Explorer > Save directory structure) of the folder `/data/user/0/com.kingouser.com`.

I suspect there might be some buggy versions out there that name their cache folder `cahce` instead of `cache`, likely a typo by the dev, but it leads to the cache not being managed.

**Comment by randomname1234** [comment]
Trying to save directory structure of '/data/user/0/com.kingouser.com' return "failed"

I will provider the log tomorrow

**Comment by d4rken** [comment]
@randomname1234 Any update on this?

**Comment by randomname1234** [comment]
Sorry, I forgot about this.

So, I tried with 4.2.6 (the version you send me yesterday) and the problem seems solved. 
KingoUser version 2.1.2
This is the pathdumps [http://hastebin.com/vobaqiqiba.avrasm](http://hastebin.com/vobaqiqiba.avrasm)

Here is the [log](https://gist.githubusercontent.com/randomname1234/03598e4c5ae92ab531681fc51f927391/raw/66575a31c5a0c877883a976e97059734c4f0a7da/sdmaid_logfile_1466335382093.log)

I also tried to delete an app located `/vendor` as you asked me for a log in the mail

**Comment by d4rken** [comment]
Thanks, nothing unordinary in your KingoUser files. Closing this one as the log I saw was likely a fluke.

(I have also edited your post and added the uninstall log to the appropriate ticket. Remember that tickets are all about keeping related information toegether for future searches and investigations).
