### ISSUE TITLE
Clutterreport: /storage/emulated/0/Movavi Clips (new)

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3839]
### Target
Target: `/storage/emulated/0/Movavi Clips`
Prefix-free: `Movavi Clips`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Movavi Clips`
Packagename: `com.movavi.mobile.movaviclips`
Version: `4.1.0 (57)`

### Current owners
None

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by Ingood5** [comment]
Если я просто помечаю папку как принадлежащую приложению, но не знаю нужно ее сохранять или нет, то мне нужно просто пометить ее как keeper, или нужно ещё дополнительно написать, что я не знаю, keeper это или нет?

**Comment by d4rken** [comment]
> If I just mark a folder as belonging to the application, but I don’t know if I need to save it or not, then I just need to mark it as keeper, or do I need to additionally write that I don’t know if it is a keeper or not?

If you are unsure, mark it as "keeper" and tell me in the comment that you are unsure.
If possible, tell me about the item inside. :+1: 

I will then also check, and if necessary use a different option. Generally, files that are created the camera, like videos or pictures flagged with "keeper".

But in the end the "keeper" flag is only a little extra precaution such that the user has to enable the option for them to be visible.

**Comment by Ingood5** [comment]
Почти все отчёты, которые я, отправил 31 июля а также в августе, я не проверял и отправил как keeper, подразумевая что папка принадлежит приложению, но это не keeper. Вы поняли, что это не keeper? Иначе надо все эти отчёты перепроверить. Или мне нужно прокомментировать отчёты, которые нужно перепроверить?

**Comment by d4rken** [comment]
I don't think they need to be rechecked. Most reports were very good :+1: , if I had doubts, I commented on them.
I already adjusted the `keeper` value for reports where I think that it should be different.

https://github.com/d4rken/sdmaid-public/issues?q=is%3Aissue+author%3AIngood5+label%3A%220+c%3A+Definitions%22+

Example:
https://github.com/d4rken/sdmaid-public/issues/3725
Here the report says  `keeper=true`, but I added it with `keeper=false`, because usually the `.dot` files/folders are attempts by an application to hide files from the user and to keep track of identifiers, even on reinstall, which I think most users don't want. The the most common cases where a `.dot` item should have `keeper=true` is when it related to an encryption app that creates a hidden storage.

https://github.com/d4rken/sdmaid-public/issues/3447
Here you didn't add `keeper`, but I added it, because I think the app might store it's photos here.

Maybe for the future we can just write 1 sentence about the type of files that are inside a folder. Then it's also easier to decide if it should be marked differently.

In cases where it is not clear, I always go with the safer option and mark them as `keeper'. So in the worst case, SD Maid deletes a bit less by default.

Power users can always enable the option "Show desirable remnants". 
![Screenshot from 2020-08-30 12-38-49](https://user-images.githubusercontent.com/1439229/91657535-019f6600-eac2-11ea-801d-4cadd2422237.png)
