### ISSUE TITLE
Running CCleaner after SD Maid in order to make SD Maid even better

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#395]
I find that nothing competes with SD Maid.  It is excellent.

That said, you may find it helpful to run CCleaner after running SD Maid in order to help you improve SD Maid.  Doing this on every major version of Android will yield the most helpful results.

Sometimes CCleaner does find things that SD Maid does not.

One area that CCleaner does seem to consistently "beat" SD Maid at is app cache cleaning.  It's a tricky topic, because it varies depending on Android versions.  Yet, overall, I find that even after running SD Maid, CCleaner still finds a fair amount of app cache to clean.

Ideally, after running SD Maid, CCleaner will find nothing to clean! :-)

**Comment by d4rken** [comment]
Can you show me some screenshots?
What is "a fair amount"?

What Android version and is SD Maid running with root?

**Comment by Gitoffthelawn** [comment]
Great questions.

I'm overbooked right now, but I'll try to get you any information you need.

I can type faster than I can take screenshots and post them, so I would prefer to relate info to you in text form.

I performed testing on a rooted KitKat device.  SD Maid was given root privileges.

Typically, CCleaner finds about 10-50MB of cache that SD Maid does not find.  Some of this cache is likely from apps that are running, but I don't think all of it is.

CCleaner also finds and clears clipboard entries.  CCleaner does *fail* on multi-clipboards included by manufacturers.  Maybe you can include this functionality in SD Maid?

CCleaner also detects 1 or 2 empty folders *possibly* not deleted by SD Maid.  I need to perform more testing to determine if these are just folders that are recreated as soon as they are deleted by SD Maid.

Overall, I find SD Maid to be superior to CCleaner.  Hopefully this information will help you make it even better.

I'm going into meetings for many hours now.  Feel free to respond, and I'll do my best to help you as soon as I have time.

**Comment by d4rken** [comment]
> Typically, CCleaner finds about 10-50MB of cache that SD Maid does not find. Some of this cache is likely from apps that are running, but I don't think all of it is.

The AppCleaner shouldn't skip running apps by default.

AFAIK CCleaner uses reflection to pull cache info from the system. It should show the same as the system shows in each apps info.

There are two things that can cause this:
* The Android system includes more in its cache size calculation than it actually deletes when deleting cache, specifically some top-level directories.
* The difference between size in used blocks and actual file size ([see du vs ls](http://serverfault.com/questions/290088/what-is-the-difference-between-du-h-and-ls-lh)). I think the system (and thus CCleaner) uses the size in blocks, while SD Maid uses the actual file size. This could explain the size difference.

To further look into this you would have to find a specific app that is listed in CCleaner, but no longer in SD Maid, and check the default cache folders which is what the system checks (/data/data/<pkg>/cache and /sdcard/Android/data/<pkg>/cache).
The Explorer has an action "Save directory structure" which can help with that.

> CCleaner also finds and clears clipboard entries. CCleaner does fail on multi-clipboards included by manufacturers. Maybe you can include this functionality in SD Maid?

I think that's not something we need. "Clearing the clipboard" consists of copying something random to replace what is currently in the clipboard. There is no performance or space gain here as the clipboard just contains references, maybe a few KB of text at best.
Clearing multi clipboard apps is something that we could teach the AppCleaner, but as you mentioned this needs specific code on a case by case basis, if you have such a clipboard app, make a new ticket for that and provide some details.

> CCleaner also detects 1 or 2 empty folders possibly not deleted by SD Maid. I need to perform more testing to determine if these are just folders that are recreated as soon as they are deleted by SD Maid.

Might be the few top-level directories I previously mentioned. SD Maid excludes them because they are recreated by the system.

**Comment by Gitoffthelawn** [comment]
Real quick... my meetings added an extreme amount of work to my overbooked schedule... ugh!

In regards to the clipboard stuff, I agree, it's more of a privacy issue than a storage space issue.  Features like that could help extend the userbase and appeal of SD Maid.

In regards to everything else.  I agree with everything you wrote.  The only thing that was a bit confusing was when you wrote "might be the few top-level directories I previously mentioned".  Where did you mention that?  I think I missed it or maybe you accidentally edited it out.

I truly regret that I don't have more time right now to help you out, given that you have created such a useful tool for us all.  I can, however, offer a recommendation that might help: On several devices with different versions of Android, install CCleaner along with SD Maid.  Run SD Maid, clean things, and then run CCleaner (don't forget to enable all it's cleaning modules first - some might be disabled by default).  See what CCleaner finds that SD Maid did not.

At the worst, you'll have confirmation as to the effectiveness of SD Maid.  At the best, you'll find some areas in which you can improve SD Maid.

**Comment by d4rken** [comment]
> The only thing that was a bit confusing was when you wrote "might be the few top-level directories I previously mentioned". Where did you mention that? I think I missed it or maybe you accidentally edited it out.

In some cases, the system includes the top level folder (i.e. "cache" in the size calculation, but doesn't delete it. So it (example) does sizeof `...../cache`, but deletes `..../cache/*` this skews results by a few KB as SD Maid does not include these top-level folders in it's calculation (and doesn't delete them). There are usually 2-3 top-level cache folders per App (private internal,public internal,public external) this comes to at least ~16KB (4096 block size) per app.

I've run both CCleaner and AppCleaner and can find no unusual discrepancy between the results. There are some different values due to the above and differences in size calculation.
CCleaner (or rather the system) shows a few 56KB and 60KB entries for apps that are not listed in SD Maid, but checking these apps cache directories in a root terminal I see they are actually empty. Pressing "clear cache" on the systems app info page does not change the cache size either, so I would chalk that up to some kind of system glitch.

For there to be a real difference between results, the Android system would have to include more than the default cache directories in what it calls "cache" or SD Maid would have to fail to scan a default cache directory. If you find such a case then we could investigate further, otherwise I don't think there is something being missed.

**Comment by Gitoffthelawn** [comment]
Just some quick thoughts that might be helpful: In CCleaner, you just click *Analyze* and then are presented with the results.  It's pretty fast.

With SD Maid, you have to run the CorpseFinder, the SystemCleaner, and then the AppCleaner to perform the analysis.  It takes a bunch of clicks and has to scan everything three times, which is comparatively slow.

That's not a criticism though... just an observation.  The **end results** matter just as much as how long it takes and how many clicks it takes, and SD Maid is superb (perhaps unparalleled) in that regard.

I wonder if, in SD Maid, a single scan could perform all three operations at once, with a single results pane.  If so, potentially, that could be much faster.

Those are just some quick thoughts that I wrote down hoping they might be helpful to you. :-)

**Comment by d4rken** [comment]
> Just some quick thoughts that might be helpful: In CCleaner, you just click Analyze and then are presented with the results. It's pretty fast.

You do the same in SD Maid, click "Scan" in QuickAccess and are presented with the results. SD Maid takes longer, but for what it actually does, I think it's pretty fast.

AFAIK CCleaner largely only checks the default cache folders, which is fairly fast to do as the pathes are exactly known, e.g. `/sdcard/Android/data/<packagename>/cache/`.  If we exactly know the cache location we can directly read the content, but you don't even have to scan the default folders because the system knows the cache size (what you see under app info) and you can get that information.

SD Maid takes longer to scan because it does not rely on what the system says, but reads every folder (that matches certain criteria) itself.  Furthermore CCleaner (and many other apps) only deal with top level directories, if the directory is `eu.thedarken.sdm/cache` then all it's content is cache. Done. SD Maid checks each item in a folder and allows you to exclude items within that cache directory or only delete files that are older than a specific date.

For maximum speed, we don't need an app, you can just click "Clear Cache" in the system storage settings, which is also why other apps are so fast, because they do exactly that programmatically (except this doesn't work anymore since Android 6.0 :grin:).

SD Maid is so superb because it puts thoroughness, control and insight above all else and this is achieved by not taking shortcuts, but doing a lot of manual work.

> With SD Maid, you have to run the CorpseFinder, the SystemCleaner, and then the AppCleaner to perform the analysis. It takes a bunch of clicks and has to scan everything three times, which is comparatively slow.

You can run all actions with a single tap (including scan & delete) in the QuickAccess page.  Merging them toegether doesn't make sense as each category has specific purposes.

> That's not a criticism though... just an observation. The end results matter just as much as how long it takes and how many clicks it takes, and SD Maid is superb (perhaps unparalleled) in that regard.

I see this differently, what matters are mostly the results, speed and convinience are nice to have.

> I wonder if, in SD Maid, a single scan could perform all three operations at once, with a single results pane. If so, potentially, that could be much faster.

It would be exactly the same speed. We still have to run the same operations, whether we display that that in one or multiple boxes has no noticeable performance impact.

> Those are just some quick thoughts that I took a few minutes to type in hoping they might be helpful to you. :-)

:+1:

**Comment by Gitoffthelawn** [comment]
Thanks for your response! :+1: 

> SD Maid is so superb because it puts thoroughness, control and insight above all else and this is achieved by not taking shortcuts, but doing a lot of manual work.  

Yes! :+1:   
  
> That's not a criticism though... just an observation. The end results matter just as much as how long it takes and how many clicks it takes, and SD Maid is superb (perhaps unparalleled) in that regard.

>> I see this differently, what matters are mostly the results, speed and convinience are nice to have.

I think your interpretation of my comment was a result of poor phrasing (by me).  Sorry.  I agree, the end result is the most important thing for a tool like this. For SD Maid, speed and usability are very important, but the end result is the key.  SD Maid is definitely superb in this regard.

> I wonder if, in SD Maid, a single scan could perform all three operations at once, with a single results pane. If so, potentially, that could be much faster.

>> It would be exactly the same speed. We still have to run the same operations, whether we display that that in one or multiple boxes has no noticeable performance impact.

Yes, combining the results will not increase speed.  But could scanning all the directories in one sweep (instead of separate sweeps for the CorpseFinder, the SystemCleaner, and then the AppCleaner) be faster?

**Comment by d4rken** [comment]
> Yes, combining the results will not increase speed. But could scanning all the directories in one sweep (instead of separate sweeps for the CorpseFinder, the SystemCleaner, and then the AppCleaner) be faster?

Yes it would, but then we would run into memory issues as we would have to keep everything in memory so each tool can process it. SD Maid already has problems with peak memory use on low end devices with many files.

**Comment by Gitoffthelawn** [comment]
Thanks for the great explanation!
