### ISSUE TITLE
Switching pages while worker is active leads to crash

### ISSUE THREAD

**Issue by TioCareca** [d4rken/sdmaid-public#404]
> Fingerprint: samsung/kltexx/klte:6.0.1/MMB29M/G900FXXS1CPC8:user/release-keys

crash when using system cleaner and app cleaner at same time...

**Comment by TioCareca** [comment]
S5 kltevzw developer edition with RR Marshmalow

**Comment by TioCareca** [comment]
[sdmaid_logfile_1465151819843.log.zip](https://github.com/d4rken/sdmaid-public/files/299473/sdmaid_logfile_1465151819843.log.zip)

**Comment by d4rken** [comment]
> Install ID: d5c59928-afd4-4b79-b578-ca5e2fb7bf0e

Can't find a crash report under your install ID.
Checking for SM-G900F i only see AppControl related crashes.

Debug log looks ok but seems to stop short. And this only happens if both tools run parallel? In sequence it doesn't crash?

According to the log, you have root. Can you use a logcat app to get the crash stacktrace?

**Comment by TioCareca** [comment]
Yes happens using both at the same time...
I will send the bugsnap error from your app, about the logcat whats the best app to do it?



Em 5/06/2016, 20:23, em 20:23, Matthias Urhahn <notifications@github.com> escreveu:

**Comment by d4rken** [comment]
I usually log from a computer via adb, otherwise I use [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat), but it's a bit dated.

Did you change something, because now I also see crash reports for your ID?

The issue shouldn't be specific to a tool, it's a core UI issue where SD Maid tries to update the UI with worker progress although the UI is no longer visible.
Switching any tool page while the tool is running should make it crash if you do it at the right moment.

Got enough info to fix this, should be good with the next release.
Thanks for your report!

**Comment by Gitoffthelawn** [comment]
@d4rken You may appreciate [Logcat Extreme](https://play.google.com/store/apps/details?id=scd.lcex) or [Logcat Extreme Pro](https://play.google.com/store/apps/details?id=scd.lcexpro)

**Comment by d4rken** [comment]
It's not fixed yet ;)

**Comment by d4rken** [comment]
Fixed committed for v4.2.5

**Comment by TioCareca** [comment]
Its fixed, don't crash anymore just a little bug in animations when switching...
Thank you...

**Comment by d4rken** [comment]
@TioCareca What bug? Make a new issue ticket if you want :grin:

**Comment by TioCareca** [comment]
It flickers when switching pages, cant say fore sure of its app related as i am using cm13 and some users report the flickering in lockscreen...
