### ISSUE TITLE
Did Pro version price increase?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#412]
First, let me say that whatever SD Maid Pro costs, it is worth more! :-)

I recommend SD Maid Pro to many people.  I explain to them it's not free, but the money is well spent to support you and your development and support efforts.  I then tell them the cost.

Lately, I've gotten a several complaints that the price is higher than what I told them.  Did you raise the price?  If so, is that a temporary test?

**Comment by d4rken** [comment]
Yes, about ~4 days ago. It's not temporary.
The price increased by about ~1$ depending on country, currency and taxes.

Some fluctuation always exists due to currency adjustments, economy changes and when Google makes changes (e.g. allowing lower prices for India). Though most people don't notice these changes as they are country specific. This time it was a global change because SD Maid Pro was priced to low for what it offers and in comparison to other apps, especially other paid tools.

There is unfortunately never a "right time" to change prices, someone is always affected, seeing the old price first, only to have to pay the new one. Sorry for the complaints you have gotten, but I'm sure your friends will get their moneys worth out of it. If they are unhappy with it, they can mail me within a week and ask for a refund.

Working on SD Maid is challenging and a lot of fun, but there is no denying that money is a pretty effective motivator too!

(That all apps are priced too low for the amount of work that is put into them is a different discussion 😛)

**Comment by Gitoffthelawn** [comment]
Thanks!  Great answer!  :+1: 

If you're willing to provide the data, it will be interesting to learn if the price change results in an increase or decrease in app revenue.  That info will help everyone interested in app development.

If you chart/graph it over each month, that will be very useful.  If you don't feel comfortable disclosing the actual revenue, it's still possible to share the revenue trend: just start at 100% at some point (instead of a currency amount), and show the revenue changes as a reflection of that percentage.

An accompanying chart/graph showing the number of installations over time will also help show the impact of price deltas on app growth and acceptance rates.

As you can see, I'm interested in better understanding the relationship between app price and gross revenue.

I'm skilled at analyzing this type of data, and I'm happy to help you draw accurate conclusions, if you like.

**Comment by d4rken** [comment]
The price increase was about a week ago now, buyers for the last week decreased by 7%, but revenue increased by 15%. In the last 30days, buyers decreased by 4.3%, but revenue went up by 5%.

Looking at country stats there is no clear pattern though that shows a drop of buyer # since the day where I increased the price. Graphs per country actually show a drop of buyers until the price increase, at which point it started to increase again.
On the same day I inceased the price I also released v4.2.5, so I would think the positive influence on the number of buyers was the update release (which took production from 4.1.6 to 4.2.5).

The only thing I noticed so far is that revenue is more stable since the increase. Maybe contact me via mail in a few month and I'll see if I'll get you some trend showing charts.

**Comment by Gitoffthelawn** [comment]
That's great info!

I agree that the number of buyers probably went up due to the new release.  You've been doing quite a bit of great work lately!

As you gather more data, we can analyze the trends.

App valuation is an interesting science, because even non-paying users are definitely assets.  Gross revenue is just one element of the equation.

I agree that the new price is very fair for the quality of the product and the fact that you continue to work on it.  I tend to purchase fewer apps these days because of the amount of *abandonware*.  Most of my favorite utilities that I purchased have been abandoned by the authors and are not getting improvements or bug fixes.

BTW, when looking at the metrics, you'll have to take into account the *"Gitoffthelawn bump"*, as I recently sent out a bulk email to friends and colleagues recommending purchase of your app!  :+1: :-)

Unfortunately, the price increase happened after I sent out the email, so I got a little negative feedback that they price I quoted was wrong, but as you said, it's impossible to time these things to make everyone happy.

My only recommendation for that situation is to make an announcement before raising a price, or now do promo day (or week) when people can get it for the old price.

**Comment by d4rken** [comment]
> App valuation is an interesting science, because even non-paying users are definitely assets.

In what way? App valuation that includes "non-paying users" as assets are usually for platforms where users create accounts and can be mined for user data to show targeted ads.

> I tend to purchase fewer apps these days because of the amount of abandonware. Most of my favorite utilities that I purchased have been abandoned by the authors and are not getting improvements or bug fixes.

Can't blame the devs though in many cases. You alone purchasing the app doesn't fuel much of future development. With such cheap prices for apps even though they can equal desktop software in complexity, further development can only be paid for through a steady influx of new purchases.
If not enough new users keep buying the app, even though you bought it, devs have to abandon the app or work for free.
Selling software for a one-time fee, if users expect constant updates and improvements, is a really bad business model. Someone buys an app 4 years ago, but Android is a moving platform and 4 years later the user expects his paid apps to adopt current design guidelines and use new platform features. Implementing any of that will not generate any more revenue from any existing user. If the developer thinks these additions will not generate more revenue, then he would need other reasons than money to motivate him. Often there may be desire to support old apps but as everyone needs money, after working on projects that generate money, there may not be much time or motivation left.

I think in the future we will see many more apps with subscriptions or IAP for tokens. It was probably a bad business move from my end to not sell SD Maid v4 as new app (as bonus it would also have spared me the "V3 was so much better" people :frowning:.

Sometimes it's also not about long term, but just something that didn't pan out. You release a paid app, hoping for X amount of revenue after Y days, because you need X money  to sustain development and your current resources allow for Y days of further development. After Y days it turns out your product is not as popular as expected and further development is not sustainable. Sucks for everyone who bought it up to that point, but what else can the developer do than abandon the app?

> you'll have to take into account the "Gitoffthelawn bump",

:+1: 

> My only recommendations for that situation is to make an announcement before raising a price, or now do promo day (or week) when people can get it for the old price.

I'm not sure that would have a positive effect. I never heard of a company announcing a price increase? Also increasing by X then having a promotion by saying "now for X less" seems disingenuous. After all you want the product to be purchased for the higher price (the whole reason for the price increase). Sure it would appease a few people, but wouldn't it also upset other users who were initially content with their purchase for a higher price?

Would the amount of revenue from people who buy a product only due to a "sale" announcement, be more than the revenue from people who buy it in anycase (but after a change, generating more revenue per purchase?).
