### ISSUE TITLE
Вопрос о количестве языков в настройках.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4193]
Почему в настройках при выборе языка у многих языков по два варианта в таком виде:

1. русский [ru].
2. русский (Россия) [ru_RU].

**Comment by d4rken** [comment]
SD List is generated using the list of locales we get from the system, which is based on the localization files that SD Maid has
Will have to check  `requireActivity().resources.assets.locales`, I think the system generates `ru` and `ru_RU` because SD Maid provides `ru` and it fits both.

Not 100% sure if we can just filter some of them out :thinking:

**Comment by d4rken** [comment]
Currently not planing to change this.
