### ISSUE TITLE
Automated file sorting

### ISSUE THREAD

**Issue by anarkia47** [d4rken/sdmaid-public#425]
Merge folders option,

 I often have folders with the same name but different things inside, usually pics this is due to the many automation apps I use they sometimes create conflicts and duplicate folders... 

It would be nice if SD Maid could identify these folders and merge them together.  

You could set filters for instance only merge if folders have same name and contain same kind of files mp3, vid, gpeg etc 

Another rule example, ignore cap sensitive, dots or numbers in the file name when looking for similar 

Hope you get the idea 

Cheers!

**Comment by d4rken** [comment]
Thanks for the idea!

Can you give me a few conrete example and how SD Maid would behave in each case?

> they sometimes create conflicts

What kind of conflicts?

>  if SD Maid could identify these folders and merge them together. 

How would they be identified? What happens if we have conflicts during merging?

The idea is intresting but it borders on SD Maids scope.
Do you see this being added to an already existing tool, or would this be a new one?

**Comment by d4rken** [comment]
Closed due to inactivity, I'm still not sure how this idea would work.
