### ISSUE TITLE
Fast deletion

### ISSUE THREAD

**Issue by xxoscarxx28** [d4rken/sdmaid-public#430]
Not an actual issue, but for me deleting files one-by-one is not so efficient (it is slow). I figured out a way so that we can clear caches faster. Here is the algorithm:
1. Enlist what to be deleted and not then group them by folder. (might already be implemented) (array of groups)
2. Iterate through the array of groups for the next steps

2.a. In a folder, copy the file that is not in the group to a temporary folder.

2.b. Delete the "whole" folder

2.c. Recreate the folder then if there is a file in the temporary folder, copy it back to the recreated folder ehich will effectively delete the whole cache without affecting important files.

With this algorithm, we can delete cache folders containing too many files faster since it is deleted as a whole and we can also avoid fast NAND wearing with this. But I suggest that you might want to use this algo only if you detected that the folder contains lots of junk with a mix of important files.

And if you detected that the whole folder contains only junks. You can just store its properties, delete it then recreate it again with proper permissions (chmod) and context (chcon) from stored information

**Comment by d4rken** [comment]
> In a folder, copy the file that is not in the group to a temporary folder.

Why copy and not move? Copying would duplicate the space requirement temporarily.

 > we can also avoid fast NAND wearing with this

That's not something we have to worry about, at all. This is taken care of on driver level.

> Here is the algorithm:

This might work, but could go horribly wrong.
Imagine the system/the user/others app/battery/XY kills SD Maid during deletion. Potentially important files would basically be "deleted" as they can not be found anymore. So besides just creating the temporary folders and moving files we would need code to keep a detailed log of file transactions, code that can role back transactions and code that can resume/execute these actions if an unclean "exit" during such a deletion was detected.

Another issue would be where we are deleting and where we store the temporary files. We can not store all temporary files in public storage because we might expose previously private files. So we need another routine that detects where we could temporarily store the files. Theoretically we should store it all in private storage due to privacy concerns but privacy storage might not be large enough.

It's a creative idea, but seems fairly complex.

> And if you detected that the whole folder contains only junks. You can just store its properties, delete it then recreate it again with proper permissions (chmod) and context (chcon) from stored information

Also need to check creation dates, which would also be different if we recreate the folder.

Slow speed is primarily an issue in the AppCleaner.
The way it currently works:
Scan:
* Get all apps
* Get all folders owned by each app
* Get all files in each folder owned by each app
* Match each file against active filters, matches files will be put in the expendables-collection for that app.
Deletion:
* Go through the expendables collection in each app and delete what the user submitted for deletion (files or apps or all)

**Comment by d4rken** [comment]
The deletion command via shell for individual items is what makes it slow.

We would need to find the top most common folder for each group of expendable files for each app, then determine if there are other files in that folder that are not considered expendable. Depending on whether there are or are not, we could switch between deleting the top most folder, or each item individually.

The issue is finding out whether there are other files that are not expendable. We also have to keep in mind that we have memory constraints so we can't keep all of the found files (expendables and non-expendables) in memory.

So determining this would have to be done during scan already.

Searching files happens in two step, a first step that generates pathes where an app has files, and a second step that actually reads those locations.
Maybe we could check during the second step whether all items that are within a common subdirectory have been matched to a filter.

Scanning would so scanning would become slower, because we have to find common directories and per app, per searchpath, per sets of files that matched a filter.

Deletion is then faster because in cases where all files matched a filter, we just delete a common directory.

App details would then only show the parent directory (searchpath), not any child dirs. So we loose some details there.

Not sure how much slower the scan is if there are not many items that match. Overall keeping the scan faster seem more important than deletion because scan happens more often.
So this seems to come down to having to implement this and then check how fast or slow scan and deletion are.

**Comment by xxoscarxx28** [comment]
Hmmm... I see... Btw, folder MA (modify and access) time can be changed using touch command except the change time, so this is still not plausible I think.

**Comment by d4rken** [comment]
Wow, actually done and not as horrendeous to implement as I expected 😄 .

**Comment by xxoscarxx28** [comment]
I'm glad that I helped ^_^

On Jan 23, 2017 8:04 AM, "Matthias Urhahn" <notifications@github.com> wrote:

Closed #430 <https://github.com/d4rken/sdmaid-public/issues/430>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/430#event-932162584>, or mute
the thread
