### ISSUE TITLE
UX: Consider combining CorpseFinder and SystemCleaner

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#446]
From a UX point of view, I find it preferable to integrate the CorpseFinder and the SystemCleaner.

*Why?*

Because this is my typical workflow:  

 1. Open SD Maid
 1. Click on CorpseFinder
 1. Click on the refresh button
 1. Wait approx 1 minute
 1. Deal with results or get 'List is empty' message
 1. Press the back button
 1. Click on SystemCleaner
 1. Click on the refresh button
 1. Wait approx 2-3 minutes
 1. Deal with results or get 'List is empty' message
 1. Press the back button twice

If the CorpseFinder is integrated as a component of the SystemCleaner, then almost half of those workflow steps will be mitigated.

Furthermore, the *"action, wait, action, wait again, action"* cycle will be reduced to the more palatable *"action, wait, action"*.

**Comment by d4rken** [comment]
Both tools have very different responsibilities and combining them would not only be a lot of work but likely result in inferior performance. The tight coupeling of very different routines makes it difficult to optimize it and support future improvements to each tool.

The CorpseFinders logic works based on the idea that every file can be attributed to a specific application. Using white/black listing for different areas, using fuzzy matching and apk look ups to determine ownership. A lot of back and forth.
The SystemCleaner only cares about files and doesn't understand what an "app" is. It's more of a trickle down filter system.

So that is not going to happen.
The QuickAccess page exists to make workflows easier.
Maybe we can change other things to improve overall workflow. 
Thanks for the feedback!

**Comment by Gitoffthelawn** [comment]
Perhaps a batch option that runs them both and provides unified results.

**Comment by d4rken** [comment]
Can you elaborate "unified results" further?

**Comment by Gitoffthelawn** [comment]
Yes.  Currently, SystemCleaner provides results of multiple categories: temp files, empty folders, apks, et al.  Add CorpseFinder results as a category within that UI.

**Comment by d4rken** [comment]
A unified result screen that shows all tools could be something for the quickaccess page, not sure though how to integrate it.

**Comment by Gitoffthelawn** [comment]
That's an interesting idea.  Perhaps a *"batch"* option from the quickaccess page.  When selected, it runs whatever items the user defines as part of the batch.  The results screen would then be an amalgamation of the results.

Certain functions like Explorer and Biggest would be excluded from batch operations, because it would not make sense.  But items like the CorposeFinder and SystemCleaner could definitely be included.

**Comment by gentletumbleweed** [comment]
Please unsubscribe me , I've tried but mail keeps coming I want off your
email list thank you buck.j.mitche77@gmail.com

**Comment by Gitoffthelawn** [comment]
I'm not sure what they are requesting.  It looks like perhaps they subscribed to this thread in error.  As the repo owner, you can probably delete their post.  If they still receive emails from GitHub, they will need to contact GitHub support.  To keep things clutter-free, feel free to delete this post as well.
