### ISSUE TITLE
SD Card write test: File creation works, but deletion doesn't

### ISSUE THREAD

**Issue by NinjaBoyLao** [d4rken/sdmaid-public#456]
holy shit where do i even begin with this. on my SD card, SD Maid creates "sdm_read_write_test" thingies as files. they have no file type associated with them, not on computer either. SD Maid creates them, yet in explorer, im unable to delete them. i also don't know what exactly causes it to make these, but today, it had gotten so bad that the app couldnt even do a basic cleaning. upon inserting my sd card into my computer, i found _13,104 tests_ at the SD card root, and _9,455_ just inside "Android". what the _fuck_. _what the fuck._ please fix this asap. phone specs are moto e first gen running android 4.4.4 but about to upgrade to 5.1 when my carrier rolls it out this month.

**Comment by d4rken** [comment]
Which version of SD Maid, v4.2.13?

The files are part of a routine that helps SD Maid determine which method of access is to be used for a specific location. SD Maid creates such a file, checks if it was successful and then deletes it.

While java offers an API in form `new File(...).canWrite()` this is severely broken on in Androids chaotic storage system. Especially in the case of sdcards on Android 4.4 it will often return `true` for `canWrite()` when it is actually not possible.

The only reliable way of testing write access for these location is to actually try to write a file.

If all those files are still on your card, it means that SD Maid could create them, but not delete them. 
Why does the MotoE firmware allow `createNewFile()` but not `delete()`? Either both should work or both should fail.

I'm not yet sure how to fix this, I'm open for suggestions.
We need a way for SD Maid to test write access on Androids various storage locations.

We can't rely on the methods the system offers and can neither create a testfile because we will not be able to delete it and asking the system gives us the wrong answer. How do we test writeability in your case? 

Your upgrade to v5.1 will likely fix this for you. With with 5.0+ there is a new way of accessing storage (Storage Access Framework) which SD Maid supports.

If possible record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log) of running some tools in SD Maid, I'd like to see if there is a visible error message that helps figure this out.

**Comment by d4rken** [comment]
> but today, it had gotten so bad that the app couldnt even do a basic cleaning.

Could you elaborate on that? The test files are empty and don't consume much space. 13k files are also nothing that SD Maid should choke on.

**Comment by NinjaBoyLao** [comment]
corpsefinder got stuck trying to filter the sd card, and so did appcleaner, sd maid just kinda hung. yes, 4.2.13. and i will see but unless its set to throw errors when test file deletion fails, i doubt itll throw any. 5.1 android is coming this month also, so ill try to help you figure this out for other4.4 users

**Comment by d4rken** [comment]
I should print errors if deletion of test files fails.
If these two tools get stuck we could start with a log of the CorpseFinder getting stuck and one of AppCleaner getting stuck.

Please wait an additional 10 seconds after you think it got stuck before killing SD Maid.
You can upload the logs here or mail them.

> so ill try to help you figure this out for other4.4 users

:+1:

**Comment by NinjaBoyLao** [comment]
i waited my whole 5 hour shift at work yesterday :/ but yes im gonna be traveling today so ill do what i can

**Comment by d4rken** [comment]
No worries, do it when you find the time, I got my handsfuls with other issues too, e.g. #451

**Comment by NinjaBoyLao** [comment]
I can't for the life of me figure out how to take a bug report pls help

**Comment by d4rken** [comment]
Did you checkout 
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
?

**Comment by d4rken** [comment]
Did you figure it out @NinjaBoyLao ?

**Comment by d4rken** [comment]
Spotted this in the crashtracker, shows ~120 users being affected.
The majority are Motorola devices, ~50% are rooted, so this doesn't seem to be root related.
It's always secondary storage (i.e. external sdcard) and most cases happen in `LOST.DIR` or `WpSystem` (Windows Phone?).

Version range is all across the board from 4.1 to 6.X.

Sadly no clear pattern or reason is visible.

**Comment by NinjaBoyLao** [comment]
that seems about right. im terribly sorry for being dead for so long, school and work are swamping me

**Comment by d4rken** [comment]
To further look into this I'll need a debug log of this happening, possibly even a logcat as the system might throw somekind of filesystem errors.

**Comment by NinjaBoyLao** [comment]
i've scrapped my old phone entirely, it's gone. on a moto x pure now and this issue is not present so i unfortunately can't provide logs anymore. feel free to close whenever

**Comment by d4rken** [comment]
I've added logging for this to SD Maids automatic crash tracker, still hoping to find some kind of pattern. Thanks for the headsup anyways.
