### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data (FP)

### ISSUE THREAD

**Issue by idklol987** [d4rken/sdmaid-public#4687]
### Target
Target: `/storage/emulated/0/Android/data`
Prefix-free: `Android/data`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `OnePlus/OnePlus8TTMO/OnePlus8TTMO:11/RP1A.201005.001/2101212317:user/release-keys`

**Comment by Pablo403-60** [comment]
Hello my German friend im very sorry i still didynt done everything what i got from you but during  this long time hacking me i am very tired and i dont have everytime something like exampłe sd maid pro, to only because i needed change bank  details to buy one and sudenly again something strainght happen after i change billing adress system on my bank changed himself from sended to my   
new adress picked up from the branch and all that time 12weeks he doing non stop somveryething bad bad to me even now he swithing of e
