### ISSUE TITLE
Enhancement Suggestion - Clean Cache On Screen Off

### ISSUE THREAD

**Issue by daygle** [d4rken/sdmaid-public#4704]
Hi,

I would like to suggest an enhancement to the application. Could you please add the option to allow users to clean cache on screen off.

Other applications have this cleaning option. It would be great to see it in SD Maid.

Kind Regards
Daygle

**Comment by d4rken** [comment]
What other applications?

Cache deletion is supported while the screen is off, but using the accessibility service option is not possible because it clicks on the screen for you, which doesn't work if the screen is off.

**Comment by daygle** [comment]
The application 'Auto Optimizer' has this functionality.

https://play.google.com/store/apps/details?id=jp.snowlife01.android.autooptimization.trial

**Comment by d4rken** [comment]
Ok I missunderstood you, sorry.

I thought you meant "**while** screen is off", and auto optimizer also cannot run the accessibility based cache deletion while the screen is off.
But you meant to trigger operations **WHEN** the screen is turned off.

While technically possible, I don't think it is a good thing to do.
That's why SD Maid also has "daily" as the minimum scheduler execution interval. If you delete files (e.g. caches) that often it will only hurt your devices performance and increase battery usage.
