### ISSUE TITLE
SystemCleaner fails to detect children of directory _chartboost

### ISSUE THREAD

**Issue by Solomon1732** [d4rken/sdmaid-public#471]
When using SystemCleaner it detects the directory _chartboost, but fails to detect it's children, and shows it as 4KB in size, when in fact it's more (723KB in my case) because of the contents that are not detected.

Directory path: /storage/emulated/0/_chartboost
Android version: 6.0 Marshmallow
Phone type: LG G4 Beat

**Comment by d4rken** [comment]
During deletion the size of what is deleted is determined again.
Do you know if SD Maid showed the correct amount when it deleted the entry?

**Comment by Solomon1732** [comment]
It did show the correct amount when it deleted the entry.
As a side note, in Explorer it displayed the SystemCleaner icon along with a question mark.

**Comment by d4rken** [comment]
Do you know which app created the folder?

**Comment by Solomon1732** [comment]
I have zero idea. I wish I could give more assistance.

**Comment by Solomon1732** [comment]
What I do know is that before I deleted it, the directory contained various
pictures of apps in the app store. It contained 2 sub-directories (CBVideos
and some other one beginning with CB. The pictures were in the second
directory).
The CBVideo directory was empty.

The web didn't have mush info about the name, except that chartboost is
some advertisement company. www.chartboost.com is their website.

On Wed, Aug 31, 2016, 19:23 Shlomi Reuveni <shlomireu5@gmail.com> wrote:

>

> >

> >

> >

> I have zero idea. I wish I could give more assistance.
>
>
> On Wed, Aug 31, 2016, 19:21 Matthias Urhahn <notifications@github.com>
wrote:

>

> >

> >

> >>

>> Do you know which app created the folder?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/471#issuecomment-243818333>,
or mute the thread

**Comment by d4rken** [comment]
Don't worry.

FYI: The folder comes from the chart boost SDK which is a library that apps can integrate. We would have to know which app integrated it and then add a reference for it.

This is a common library more than one app uses, it would be added with the flag `common` causing SD Maid to know about it, but not act upon it (until I have a better solution).

Optimally we can have this covered through the AppCleaner, but in these case the SystemCleaner (which acts on file/path info) is the only solution (because we don't know all apps that own the folder).

**Comment by d4rken** [comment]
Same thing also happened for other matches in this filter. Good catch!

Fixed it in v4.3.0.

**Comment by Solomon1732** [comment]
Thanks!
