### ISSUE TITLE
Bug: Slow down in scanning 

### ISSUE THREAD

**Issue by krinstar** [d4rken/sdmaid-public#4870]
### What happened?
I used the overview to scan the options I've chosen. It start slowing down at reading system apps after a while. 

### What did you expect to happen?
Just as fast scanning as it was before.

### How can I reproduce the issue?
Just run it with the multi thread at 8

### Comments
Love your prqogram. I've used it for many years. Saved me from buying another phone back in the day. Thanks for the hard work!
### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/beyond2qltesq/beyond2q:11/RP1A.200720.012/G975USQU5GUCG:user/release-keys`

**Comment by JeffHorinzon** [comment]
Hi, friendly volunteer Spirit here.  The developer Darken mentioned in the SDMaid Discord server regarding this issue.  This issue is actively a problem of Google with their new Storage Access Framework, which is needed for Android 11 to access and scan the system thoroughly.

From what I heard even outside of SDMaid universe, SAF seems to have brought trouble to developers for being slow and poorly executed.  Therefore, there's nothing for SDMaid to do about this.  

You may need to wait for either Google giving exclusive permission special access to SDMaid or Google scraps this API.  Thanks for reaching out tho.  I, a normie, too am quite frustrated by its slow speed (someone who cleans 4GB+ or stuff regularly).

**Comment by d4rken** [comment]
Closing in favor of #4886
