### ISSUE TITLE
Accessibility service is enabled, but system is not launching it.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4955]
### What happened?
Если ненадолго свернуть SD Maid, то служба спец возможностей перестает работать,  хотя остаётся включенной в настройках телефона, принудительное отключение и включение не помогает. Проблема исправляется если подождать немного дольше, возможно служба окончательно завершается (т.к. сама отключается в настройках телефона), после этого ее можно включить и будет работать.

[sdmaid_logfile_1624944308459.txt.zip](https://github.com/d4rken/sdmaid-public/files/6730883/sdmaid_logfile_1624944308459.txt.zip)

https://user-images.githubusercontent.com/60130882/123742587-9591b800-d8b4-11eb-96d4-a5f250598dd5.mp4

                                   

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.10.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
The system toggle is not a "start button", the accessibility server will be started asynchronously at some point later (usually very shortly).

The system may decide though that the service missbehaved and punish it for that by not starting it again until reboot.
Does a reboot fix it?

I have personally only observed that the system punished the server, if it crashes. So SD Maid has some code that will voluntarily disable the service instead of crashing, so the system will not punish it. But if this has happened, then the toggle should be off :thinking: 

I have heard from some MIUI users that battery saving options caused the service to be stopped. I currently don't have a reliable workaround available.

I'll look at your log later, but it seems like the system is just not launching the service.

**Comment by Ingood5** [comment]
Как я писал выше, можно подождать дольше, тогда служба отключается в настройках и проблема исчезает. 

Для SD Maid у меня работа в фоне запрещена, я не написал об этом выше. Я включаю службу только если это нужно для отправки отчёта. Но если эта ошибка из-за ограничения работы в фоне, то все равно, как вы написали, служба должна полностью отключиться. 

То есть происходит следующее. Я запускаю SD Maid (для него работа в фоне запрещена), включаю службу, далее ненадолго сворачиваю SD Maid (надеясь что операционная система не успеет выгрузить SD Maid из памяти), спустя небольшое время разворачиваю SD Maid, и обнаруживается названная проблема.

**Comment by d4rken** [comment]
Currently don't see a way to fix something on my end.
For MIUI devices, @JeffHorinzon has reported that enabling "Autostart" in the system settings for SD Maid, improved things a lot.

**Comment by d4rken** [comment]
Nothing I can do from my end here.
User reports indicate that enabling "Autostart" for SD Maid, helps on various ROMs.
Also see:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
