### ISSUE TITLE
AppControl feature request

### ISSUE THREAD

**Issue by DO97** [d4rken/sdmaid-public#503]
1. It would be very useful if there's the possibility to show the option to enable system apps displaying directly in AppControl section. (Not-system apps loading is faster and I select it by default, but if I need to check a system app I'm forced to move on settings.

2. The deletion of apps cache is a possible feature?

**Comment by dukelc** [comment]
![1](https://cloud.githubusercontent.com/assets/16635770/18652053/975366d2-7ecf-11e6-82fc-ccf8ccffc5d1.png)
![2](https://cloud.githubusercontent.com/assets/16635770/18652054/976e8dae-7ecf-11e6-851c-0e259d82864d.png)
![3](https://cloud.githubusercontent.com/assets/16635770/18652055/977d069a-7ecf-11e6-819d-01dcbceb7c34.png)
![4](https://cloud.githubusercontent.com/assets/16635770/18652056/977ea87e-7ecf-11e6-8dc8-819525e1ddcf.png)

**Comment by d4rken** [comment]
Regarding1: 
* Where would you place the setting in the AppControl UI?
* How often do you have to switch that? It's 4 taps to switch the setting.
* Are you using the faster loading (preload app estates disabled)? Loading the whole list already takes only a few seconds.

Regarding2:
Do you mean cache cleaning from the AppControl page?

**Comment by DO97** [comment]
Regarding 1:
1. Maybe on top of the 'extras' sidebar.
2. I prefer a faster loading, but the time when I need to check a system app, I need to prefer the system app manager.
3. No, it's disabled.

Regarding 2:
Right.

**Comment by d4rken** [comment]
1: Hm i think it's a bit superfluos. I actually even thought about removing the "include system apps" setting altoegether since the introduction of faster scanning and new filtering.
How much speed difference is there on your device?

2: Possibly, but I'm a fan of keeping each tools responsibilities sepperated. Note, that this wouldn't be much faster than running the AppCleaner itself because it will still have to scan the whole device to find and map all files. The feature would call the app cleaners code but throw away any other results as to keep things maintainable code should be reused as much as possible.

This might also be a bit confusing for the user as it's not necessarily visible what cache files will be deleted, especially as what counts as cache file, depends on which AppCleaner filters are enabled...

**Comment by NeoBeum** [comment]
Another feature that would be nice is to have a drop down for Sort

**Comment by d4rken** [comment]
@NeoBeum Can you create a sepperate ticket for that?
