### ISSUE TITLE
SD Maid deletes WhatsApp Stickers

### ISSUE THREAD

**Issue by SaktisImpreza** [d4rken/sdmaid-public#5121]
Running SD Maid will delete self-made stickers on WhatsApp using Sticker.ly. Kindly take a look at it.

SD Maid Pro version: 5.1.10

**Comment by d4rken** [comment]
Please provide a debug log or additional information about the paths and where in SD Maid they are being deleted.

**Comment by SaktisImpreza** [comment]
> Please provide a debug log or additional information about the paths and where in SD Maid they are being deleted.

How can I provide a debug log to you? Enlighten me please :)

**Comment by dragonGod97677** [comment]
@SaktisImpreza here https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug

**Comment by SaktisImpreza** [comment]
No fixes? @d4rken

**Comment by d4rken** [comment]
Sorry, dropped of my radar.

@SaktisImpreza 

> Now, head to SD Maid and start scanning

Just scanning or also deletion?

Can you try just pressing "clear cache" on WhatsApp, without using SD Maid?
If the stickers are also lost, then there is nothing I can do.
If the stickers are still there, then the issue is SD Maid specific and I can do further research.

@YourMama69 
> I even tried to exclude WhatsApp folder but it doesn't work.

I currently think it's just the "Clear cache" button, e.g. the system default routine causing this, if that is the case, excluding the public WhatsApp folder will not prevent SD Maid from clicking the clear cache button, you'll have to completely exclude WhatsApp by packagename.

**Comment by SaktisImpreza** [comment]
@d4rken Thanks for your quick response.

After excluding the package name "com.whatsapp", it solved the problem.

Thanks!
