### ISSUE TITLE
Some partitions and Android/Data are not read by SD Maid

### ISSUE THREAD

**Issue by ianz56** [d4rken/sdmaid-public#5182]
The latest version of SD Maid (5.3.5) overview cannot read some partitions, such as /data and /mnt/expand/... And on the explorer the folder .../android/data/ is also unreadable by SD Maid both internal and external storage.

But in previous versions SD Maid (The one I use is 5.3.1) can do just that.

[Screenshot_20211115_071722](https://user-images.githubusercontent.com/41635087/141704886-d61ab4bb-b458-439e-afaa-c8a18a2fed6a.jpg)
[Screenshot_20211115_071012](https://user-images.githubusercontent.com/41635087/141704888-92b7ce97-97b9-48ab-9101-07fde13a771c.jpg)
[Screenshot_20211115_064651](https://user-images.githubusercontent.com/41635087/141704889-b3117c1f-bbef-4108-9222-98e0cf468d54.jpg)
[Screenshot_2021_1115_064406](https://user-images.githubusercontent.com/41635087/141704890-a25e9af1-25fd-474c-ab38-854f58ef3b0a.jpg)

Debug log: [The link](https://drive.google.com/file/d/19nUxE39npRdbXj3HYF92Pr-eGVaG-sBW/view?usp=drivesdk) 

Smartphone:
 - Device: Vivo Y12s 2020
 - OS: Funtouch OS 11 Global based on Android 11

**Comment by d4rken** [comment]
> The latest version of SD Maid (5.3.5) overview cannot read some partitions, such as /data and /mnt/expand/... And on the explorer the folder .../android/data/ is also unreadable by SD Maid both internal and external storage.

Unless you were rooted, I don't think you could read `/mnt/expand/....` as that's private secondary storage.

`/Android/data` is generally not readable anymore without root on Android 11+ unless your ROM has specific OEM modifications that undo Google's changes (I have not seen that yet).

There was a brief period where SD Maid could still read `Android/data` due to legacy modes applying and SD Maid not targeting the latest Android versions. This worked in Android 12 beta, but broke in Android 12 final, and November 1st was also the deadline for targeting newer Android versions.

So I expect it to work like this actually :frowning:, one thing you can try is:

Go to SD Maid options > advanced > storage access.
See if you can grant access to the root of your storage e.g. select `/storage/emulated/0`.

**Comment by d4rken** [comment]
Some access will be restored by #5183, please reopen if the issue still persists after the next update.

**Comment by swilger** [comment]
Hi darken, i Hope i do this right, pls Tell me how i am able to Help fix. I am noob on Android, but Got fair skillz on ibm-pc, ive grown Up with 🫣 i really appreciate SD MAID quite some time, i never Had any big issues.
# Samsung Galaxy Note 8, A12.1 rooted with Magisk canary build (25.202) (33), SD MAID 5.4.1 PRO
Under settings-general settings-advanced settings-setup
Grant Storage Access to storage/emulated/0 is success.
Permission is sucess on internal storage. External storage Red ERROR ON ACTIVITY_OPEN_file_tree.
I know that is Something to fo with the custom rom. But what is to fix, what is need to implement there. I can ASK in xda the Developer of the Rom to fix? Or do i miss Something..
![Screenshot_20220821-102857_Lawnchair](https://user-images.githubusercontent.com/7537128/185782912-ea8ce8d5-fc35-4bd3-8512-312ba4d6b73c.png)
![Screenshot_20220821-102845_Lawnchair](https://user-images.githubusercontent.com/7537128/185783114-125975f1-78b0-40eb-af98-1a73537af8d7.png)
![Screenshot_20220821-102806_Lawnchair](https://user-images.githubusercontent.com/7537128/185783122-2bc84413-fbc6-413e-ae37-5a8cab8e26c0.png)
