### ISSUE TITLE
FIX THE LATEST VERSION

### ISSUE THREAD

**Issue by randomdude699M** [d4rken/sdmaid-public#5186]
**Describe the bug**
Totally unusable no need to explain. Of there's only way I can roll back to previous version I will definitely roll back. This latest version SUCKS on MIUI 12.5.5 global. (All permissions are granted including root!)

**To Reproduce**
Steps to reproduce the behavior: I don't have time typing all the shit. I can just send an email containing the screen recorder but you're ignoring it.

JUST FUCKING FIX THE APP ON 12.5.5 MIUI GLOBAL PLEASE. THIS LATEST VERSION IS TOTALLY ASS. BEEN USING THE CRACK FOR NOW SINCE MY MONEY IS WASTED ON THE LATEST UPDATE.

**Smartphone (please complete the following information):**
 - Device: MI 10T Pro
 - OS: ANDROID 11 | MIUI 12.5.5 (GLOBAL)

**Additional context**
The latest version is super ass.i.

**Comment by d4rken** [comment]
* Use nicer language, otherwise this will be closed
* Provide a description of the issue, "not working" is the same as telling your mechanic "car doesn't drive", sharing a video of the issue could also work
* Record the problem on a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) in combination with a video would be the most useful

**Comment by randomdude699M** [comment]
I LOVE YOU DADDY
