### ISSUE TITLE
Issues With MIUI Optimisations

### ISSUE THREAD

**Issue by ShinjuSenju** [d4rken/sdmaid-public#5191]
With MIUI optimisations turned off, SD MAID accessibility service takes a lot of time to clear cache

**Comment by d4rken** [comment]
This currently not supported. SD Maid takes long because it fails.

To add this functionality I'd need:

* A way to detect whether `MIUI Optimizations` are enabled or disabled
* A video showing the fastest way to clear caches with optimizations off
* A debug log recording of what was demonstrated in the video

**Comment by ShinjuSenju** [comment]
https://drive.google.com/folderview?id=1ReOJBer8EDe-qHTAMZZNE0cOmzmFnz9L
Heres a log along with the video for miui optimisation issue
And for a way to detect miui optimisation...I don't know exactly how but vanced manager is able to detect it...

**Comment by d4rken** [comment]
Currently infeasible to do anything here from SD Maids end.
