### ISSUE TITLE
Scheduler countdown reset automatically at 00:00

### ISSUE THREAD

**Issue by ansonlinh** [d4rken/sdmaid-public#529]
For example, I set a scheduler (running at 23:00 every three days) this morning, and the countdown shows about 60 hours left. When time is up to 00:00, the countdown will be reset to 71 hours. In another words, if I set a scheduler which interval is higher than one day, the task will not be executed forever.
My system: 5.1.1 HUAWEI EMUI 3.1

**Comment by d4rken** [comment]
If you have time, can you follow these instructions here:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
and make SD Maid "ready" to record a debug log, but don't open SD Maid until after 00:00.

Steps:
* Start some time before 00:00
* Long press settings
* Select "Create debug trigger"
* Force close SD Maid through the system UI
* Wait until after 00:10 or any other time where the countdown is reset in your experience
* Now open SD Maid and visit the scheduler page
* Mail me the log file or post it here.

With some luck this might give us more help because SD Maid usually writes timing information into the log when the countdown is restored.
