### ISSUE TITLE
Bug: Storage Analyzer can't delete files

### ISSUE THREAD

**Issue by FXCROG** [d4rken/sdmaid-public#5325]
### What happened?
Storage Analyzer can't actually delete files in /data/data.Except GMS and SD Maid folders.When you refresh,the "deleted" files appear again.

### What did you expect to happen?
Successfully delete files with Storage Analyzer in /data/data.I think it has something related to Android 12 and Root access.

### How can I reproduce the issue?
Android 12+Root access.SD Maid Storage Analyzer.Go to /data/data .
[sdmaid_logfile_1644045618456.txt.zip](https://github.com/d4rken/sdmaid-public/files/8007598/sdmaid_logfile_1644045618456.txt.zip)
Delete some files that is not included in GMS and SD Maid folders.Then refresh the list.See if the files were actually deleted.

### SD Maid
Version: `5.3.11 (50311)`
Pro: `isPro=true || isComplete=false (unl=true, iap=null, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/redfin/redfin:12/SQ1A.220105.002/7961164:user/release-keys`

**Comment by d4rken** [comment]
Hm, in light of #5326 I see the confusion.
For the storage analyzer I add some magic to make it seem like everything is still in `/data/data`.

So it seems deletion doesn't work correctly due to this special behavior, but it also increases confusion due to the real perspective being shown by the explorer. :thinking: 

Path wise `/data_mirror` is on not "in" `/data`, but both `/data_mirror` and `/data` share the same storage device.... :angry: 

Maybe keep it like it is now in storage analyzer but change the displayed path? :thinking:

**Comment by d4rken** [comment]
Cleanest solution might be to add an extra level to storage analyzer, so the TOP level item is the storage device, and then on a sub level list both `/data` and `/data_mirror`, not sure how much work this is...

**Comment by FXCROG** [comment]
> 

I can use Root Explorer to delete those files.Maybe this is useful information.

**Comment by FXCROG** [comment]
> Cleanest solution might be to add an extra level to storage analyzer, so the TOP level item is the storage device, and then on a sub level list both `/data` and `/data_mirror`, not sure how much work this is...

I found the easiest solution.You just need to show /data_mirror instead of /data in Storage Analyzer for Android 12 devices.Thanks.

**Comment by FXCROG** [comment]
> Cleanest solution might be to add an extra level to storage analyzer, so the TOP level item is the storage device, and then on a sub level list both `/data` and `/data_mirror`, not sure how much work this is...

I found the easiest solution.You just need to show /data_mirror and /data in Storage Analyzer for Android 11+ devices.Thanks.

**Comment by d4rken** [comment]
Not as easy as I thought, the top level device to then show /data and /data_mirror as subdevices didn't work out.
Worked 5 hours on it, no dice, it's just not possible to reliably determine the common underlying storage.

Android's storage is such a clusterfuck :angry:.

After deleting 5 hours of work, I found a better solution, should have thought about that first, the search only shows it correctly because it reads the data via a shell that has a modified mount space, I just need to force the deletion shell to use the same mount space and it works just fine :roll_eyes:.

Fixed in the next update.
