### ISSUE TITLE
Unable to extract library apps

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#5379]
В AppControl есть тип приложений - библиотеки, их нельзя извлечь. Так специально задумано?

![Screenshot_2022-03-03-15-23-59-530_eu thedarken sdm](https://user-images.githubusercontent.com/60130882/156565041-2d157009-0b01-427f-b25f-7a8714dcd3ef.jpg)

**Comment by d4rken** [comment]
Yes, this is by design.
SD Maid does not support extracting these files (or installing them).

SD Maid internally has to detect these so the CorpseFinder works correctly, but they are not too useful outside of that.
I just thought that if SD Maid can already detect these, then I could also show them in the list to give "a complete picture".
But there is nothing that can be done with them from SD Maids point of view.
