### ISSUE TITLE
Clutterreport: /storage/extSdCard/shopeeTW (new)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#543]
### Target
Target: `/storage/extSdCard/shopeeTW`
Prefix-free: `shopeeTW`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `蝦皮拍賣`
Packagename: `com.shopee.tw`
Version: `2.4.38 (75)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

**Comment by david082321** [comment]
i use XinternalSD, so the path (/storage/emulated/0/) have become to /storage/extSdCard/

**Comment by d4rken** [comment]
Great report, thanks again.

If SD Maid correctly detected the location (i.e. `SDCARD`) then `/storage/emulated/0` or `/storage/extSdCard` does not matter because SD Maid will map this dynamically on the users device.

So on your device SD Maid will have a list for `SDCARD` with:

* `/storage/emulated/0`
* `/storage/extSdCard` 

and from that generate the entries:

* `/storage/emulated/0/shopeeTW`
* `/storage/extSdCard/shopeeTW`

because both locations are of the same type.

**Comment by david082321** [comment]
ok! i understand.
Thanks.
