### ISSUE TITLE
Clutterreport: /storage/extSdCard/voicenote (new)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#549]
### Target
Target: `/storage/extSdCard/voicenote`
Prefix-free: `voicenote`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `讯飞语记`
Packagename: `com.iflytek.vflynote`
Version: `2.0.1111 (179)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

### Comment
`TTS (Chinese)`

**Comment by d4rken** [comment]
"voicenote" sounds like something user generated. Might this be something the user wants to keep even if the app is installed?

**Comment by david082321** [comment]
yes, it must be.

**Comment by david082321** [comment]
it's TTS data

**Comment by d4rken** [comment]
Ok, you can check the "keeper" checkbox in the report screen if you think it should only be suggested for deletion if the user turned it on in settings. Usually the case for e.g. backups or pictures or voice notes.

**Comment by david082321** [comment]
if another folder have 5 folder in it.
2 of them are thumbnail & cache, →delete.
others is important data. →keeper

How shoud i report?
@d4rken

**Comment by d4rken** [comment]
Example:

```
/sdcard/AppFolder
/sdcard/AppFolder/cache
/sdcard/AppFolder/thumbnail
/sdcard/AppFolder/importantData
```

In any case, SD Maid needs to know who owns the top level folder. So report `/sdcard/AppFolder` with the clutter report tool like the others.

Also check the box for  **keeper**, because we want to keep `importantData` when the app is uninstalled.

Because all tools make use of the clutter database, when the new database entry for `/sdcard/AppFolder` is added, the AppCleaner will detect the folder named `cache` automatically 😄 .

`thumbnail` would currently not be automatically processed by the AppCleaner, but you can make an extra ticket on GitHub for it and I would add this.

Great reporting so far, let me know if you have more questions.
