### ISSUE TITLE
App Control update single app

### ISSUE THREAD

**Issue by FlyingHorseGA** [d4rken/sdmaid-public#567]
As the title says. It would be helpful to refresh a single app (or perhaps a selection) after making changes. It certainly would be more practical than waiting to refresh all 460+ apps each time.

**Comment by d4rken** [comment]
What kind of information usually changes when you need to refresh?

**Comment by FlyingHorseGA** [comment]
Nothing. I'm sorry. I'm stupid. Please just delete this whole thing.

**Comment by d4rken** [comment]
Oh?
I don't think you are stupid.

Some things should already update like killing/freezing/modifying receivers, if done through SD Maid.
But size information, even if modified through one of SD Maids tools would not automatically update.

I don't think that happens to often though, so what would be a common use case when we need to refresh app?

My first idea would have been to refresh and check whether an app is running or not...

I also don't know how fast it would be if we just refresh a single app instead of the whole list.
