### ISSUE TITLE
Spotify mercury.db Databases Freeze

### ISSUE THREAD

**Issue by Lvl4Sword** [d4rken/sdmaid-public#594]
The program works great except for an issue with Spotify's mercury.db, which is located at /storage/6431-D7FD/Android/data/com.spotify.music/files/spotifycache/mercury.db .. The database scan freezes at 5%. My entire device slows down to a crawl, and I can't even open up Gallery and view a picture. I have to hold the power button down on my device to power it off. Setting an exclusion doesn't seem to work either. I've tried /storage/6431-D7FD/Android/data/com.spotify.music/files/spotifycache/ and /Android/data/com.spotify.music/files/spotifycache/ with no luck.

**Comment by d4rken** [comment]
I've had no issues with that db, but it can sometimes take a while to process it, it's usually a quite large db too. From the path it also seems like the database is on a removable sdcard which is usually 3-4x slower than your internal storage which doesn't make the operation any faster (storage performance is the bottleneck here).

How long did you wait for it to finish?

Your whole device slowing down during that is because of how good (or bad) your device handles multi-tasking. Many devices slow down if the storage (controller) is maxed out.

**Comment by Lvl4Sword** [comment]
I've waited 8/9 hours and woke up with my battery nearly dead.

**Comment by d4rken** [comment]
Ok thats way too long, anything above a dozen minutes or so seems too long.
What size is the database file and is it at the "comparing/searching" stage or the "Optimizing" stage?

There was a bug that caused a hang in one of the earlier stages, so make sure you have at least SD Maid v4.3.8.

**Comment by Lvl4Sword** [comment]
Comparing, and I have 4.3.8

**Comment by d4rken** [comment]
Can you record a debug log?
You can abort it after it hanging for a few minutes.
So we can get an idea where exactly it is hanging at.

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by d4rken** [comment]
Any luck on recording the issue in a log?
