### ISSUE TITLE
[Feature request] Sorting the results by state/name

### ISSUE THREAD

**Issue by lisandrocarmona** [d4rken/sdmaid-public#598]
I'm not being able to find which databases are failing to be compressed. There are tons of them (all green) and can't find 2 of them that can't be managed by SDMaid. Maybe a sort option by state/name into the results list (or even in the options) will make it **easy for us to make exclusions**.

**Comment by d4rken** [comment]
Why would you prefer to exclude the failed entries, assuming no side-effects, ignoring them would also work, most failures due to schema issues fail early on not resulting in a process slowdown.

The current sortmode is database size, when would name sort be interesting and would it be appname, packagename or even filename?

**Comment by lisandrocarmona** [comment]
I agree that this particular exclusion is not absolutely necessary. Just that when running the app I can see that everything went ok and, from time to time, which new installed app is falling due to schema issues.

Sorting by state: compressed ok (green) and failed to compress (red).
Sorting by name is less important in my opinion, but I think it'll be easy for users to see appname (less people know packagename and filename android schemes).
