### ISSUE TITLE
Add previous-owner app for CorpseFinder

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#663]
CorpseFinder will find items that the user might want to delete, but it can be very challenging to find the previous owner of those files.

Perhaps, in CorpseFinder, **list the app that created each file** so the user can decide if they are really corpses.

For example, on one device, CorpseFinder is recommending the deletion of .bnr_fifo_rly and .bnr_fifo_req, but neither filename is found when searching this repo.  An internet search finds some possible owners for those files, but only SDMaid knows for sure *why* it is recommending the removal of those files.

**Comment by d4rken** [comment]
SD Maid doesn't have that information for every corpse. For locations such as the root of public storage (sdcard) SD Maid will only list files as corpses if there is a known owner that is not installed, meaning for this location items have to be whitelisted and may only then be checked and suggested for deletion.

In locations such as private data (e.g. `/data/data`) everything that is unknown is a corpse by default. So if you create a file named "santa-claus" in there, SD Maid will mark it as corpse, because the naming pattern doesn't fit in there, but we don't know who the real owner is.

So for some locations we could only say "Unknown" while for others we could say "Known owners are .... of which none are installed".

On the sdcard clutter database entries are needed to whitelist apps, to make them available for corpse checking and in areas such as private data storage, the clutter database entries are needed to fix such outliers.

Some ROMs just place random files where they don't belong and due to not fitting the naming pattern SD Maid assumes they are corpses, this is probably the case with those `.bnr_fifo_rly` files. If you can find an app that these belong to though, we add a database entry to fix this.

**Comment by Gitoffthelawn** [comment]
Okay, so you are recommending whitelisting them?

BTW, from the research I performed, it looks like they may be created by LG Backup.  Not sure if they are trash or needed.

They are located in `/data/user/0`.  What is triggering CorpseFinder to classify them as corpses?

**Comment by d4rken** [comment]
SD Maid thinks it's a corpse because it doesn't belong there, it doesn't follow naming conventions, `.bnr_fifo_rly` is not a packagename.

The best solution would to create a database entry for this if we know which app creates them.

**Comment by Gitoffthelawn** [comment]
The data in [this repo](https://github.com/dorimanx/lp_ramdisk_dorimanx/blob/master/D800-RAMDISK/init.lge.rc#L94) implies it is a backup tool installed by a device manufacturer.

**Comment by d4rken** [comment]
Is there an LG backup app? Can you search in AppControl just for "backup" and see what comes up?

**Comment by Gitoffthelawn** [comment]
On the device with those files, searching within AppControl for "backup" returns 5 results.  The relevant one is most likely *LG Backup* which has the package name of `com.lge.bnr`.

**Comment by d4rken** [comment]
Oh that was a fruitful code dive 🎆 .
* `.bnr_fifo_rly` and `.bnr_fifo_req` to `com.lge.bnr`, sounds like a perfect match, added.
* Corpse details now show ownership information.
* When checking the displayed ownership information i saw that test entries for some apps showed the same owner multiple times. Due to how the clutter database information is initiated in SD Maid, a later step that stores the data sorted by location (i.e. SDCARD) caused the data to be add multiple times. By changing the datastructure to disallow duplicates, we cleaned up the ownership details and slightly improved performance in some cases 👍.

**Comment by Gitoffthelawn** [comment]
Great job! :)
