### ISSUE TITLE
Miscategorization of osmdroid files

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#666]
CorpseFinder is reporting tile files in `/storage/emulated/0/osmdroid` as corpses, even though the app that created them is likely still installed. (I'm not 100% sure which app created them, but nothing on that device was uninstalled recently.)

Since, I believe, multiple programs can create OSM tile files, cleaning them up would be more suited as a job for SystemCleaner, and not CorpseFinder.

**Comment by d4rken** [comment]
A SystemCleaner filter just to delete the OSM files?
Hmm The issue I have with that is that it is not something that needs to be deleted regularly, but only once when the app it belongs to is uninstalled.  So the user has to keep it disabled until the app is removed, then enable it? Then he could just delete the folder by hand.

I agree it's problematic though because many apps use this folder. So it's either flagging the folder as `common` which would cause it to no longer be used for finding corpses, or we accept that it's problematic, have the user deal with it through exclusions and add clutter database entries when ever it's reported.

**Comment by Gitoffthelawn** [comment]
Yes, that's a good analysis of the situation.  Let's both think about it some more, and perhaps a  solution will come to light.

**Comment by d4rken** [comment]
I've looked into whether it's possible to detect the use of the osmdroid library inside of apps, but aside from unpacking each app and scan their resources, I could not come up with an idea, and the former idea would be anything but fast.

There are apps though which scan your apps for use of ad libraries, I wonder how they do that...

**Comment by Gitoffthelawn** [comment]
Hmmm... yes, unpacking and analyzing would be slow.

I wonder if it could be accomplished by just inspecting content providers, services, or even broadcast receivers.  All of those can be identified without unpacking.

**Comment by d4rken** [comment]
Did you look into it?

**Comment by Gitoffthelawn** [comment]
Message received.  Haven't had a chance yet.  Bumped it on my to-do list.

**Comment by Gitoffthelawn** [comment]
Okay... had a chance to look into it.  We need a small list of apps that use `osmdroid` files in order to inspect their content providers.

But before we go that route, would inspecting content providers even be an option?  Or would it be too slow?

BTW, you mentioned apps that scan your apps for use of ad libraries.  I had a good one of those, but it hadn't been updated for a couple years, so I removed it.  Do you have any recommendations?

**Comment by d4rken** [comment]
No idea about performance. Can't recommend any ad library detecting app,
but I remember that their performance was acceptable.

Am 08.01.2017 7:53 nachm. schrieb "Gitoffthelawn" <notifications@github.com

**Comment by d4rken** [comment]
Closing this topic due to inactivity, if necessary, just re-open.
