### ISSUE TITLE
Sdmaid is not queuing

### ISSUE THREAD

**Issue by kvbkiran** [d4rken/sdmaid-public#670]
Hello!
I have been using this app since a year ago its working fine, but now I have bought a new mobile and I have rooted that mobile and when I am using SDmaid it just stuck at the queuing it's not at all scanning anything.
I have reset my mobile but still not working.
I have installed the firmware again but not working.
I don't know what's happening, please help me

My phone is LYF Flame 1 (LS-4503) running 5.1.1

**Comment by d4rken** [comment]
When it displays "In queue", SD Maid is establishing its base conditions. This includes setup of binaries (toybox/sqlite), but also root detection and storage detection.

In most cases I've seen of this, it was caused by SD Maid seeing root, asking for root, but then never getting an answer.

Check your super user management application.

**Comment by kvbkiran** [comment]
My phone is rooted but it's not fully rooted it can't run shell commands directly. I think that is the problem. it's asking for root permission and its granting but even I can't go to sd maid's settings, there also it's just loading

**Comment by d4rken** [comment]
You need to either fully root your device, or unroot it, something "inbetween" is not something SD Maid needs to support.

On SD Maid v4.5.5+ there is a debug option to disable SD Maids root check, long press the settings button, activate it then restart SD Maid. It should at least no longer hang.
