### ISSUE TITLE
Editing Scheduled tasks and misbehavior of them

### ISSUE THREAD

**Issue by bradmoss** [d4rken/sdmaid-public#690]
Hi, tanks for your excellent product first!
Then my problem. I have a rooted device and I scheduled a reboot at 3:00 am every morning.
Turns out it reboots but not at 3:00 am but when I first use the device after getting up. Is this a bug?
Anyway I can't find a way of editing the scheduled task, it is just grayed out all the screen, is there a way of doing the edition?
Thanks.

**Comment by d4rken** [comment]
> Then my problem. I have a rooted device and I scheduled a reboot at 3:00 am every morning.
Turns out it reboots but not at 3:00 am but when I first use the device after getting up. Is this a bug?

I'm not sure, is this reproducable every time?

From [Androids docs](https://developer.android.com/reference/android/app/AlarmManager.html):

>Note: Beginning with API 19 (KITKAT) alarm delivery is inexact: the OS will shift alarms in order to minimize wakeups and battery use. There are new APIs to support applications which need strict delivery guarantees; see setWindow(int, long, long, PendingIntent) and setExact(int, long, PendingIntent). Applications whose targetSdkVersion is earlier than API 19 will continue to see the previous behavior in which all alarms are delivered exactly when requested. 

What Android version do you have? Does it only happen with the reboot or other tasks too?
What time does SD Maid display for the action within the statistics/history section?

> Anyway I can't find a way of editing the scheduled task, it is just grayed out all the screen, is there a way of doing the edition?

Cancel the current timer to edit something.

https://github.com/d4rken/sdmaid-public/wiki/Scheduler

**Comment by bradmoss** [comment]
Great, I canceled the timer and could regenerate the task, thank you!
Will keep watching the wakeup issue, I am a new user of your excellent program. Thanks again.
