### ISSUE TITLE
AppCleaner locks up on Nova launcher path

### ISSUE THREAD

**Issue by dieselzackab** [d4rken/sdmaid-public#717]
Hi for the last several versions the app cleaner had locked up on my Nova Launcher path trying to analyze it.  It takes forever and I usually end up ending sd app.  I'm running the newest version of sd pro

**Comment by d4rken** [comment]
Can you record a debug log of the scan until SD Maid hangs?
See:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

What ROM, what device, root?

**Comment by d4rken** [comment]
Nothing locks up. SD Maid is still working.

At the time of the log you send me SD Maid has so far processed ~20000 analytics files, e.g.

```
1485382581570 V/InteractiveShell: Output: 600:regular file:45849:944265:10284:10284:439:512:8:1469804729:`/data/user/0/com.teslacoilsw.launcher/files/.Fabric/com.crashlytics.sdk.android:answers/session_analytics_to_send/sa_a266e031-8cae-4a91-a447-c19457971267_1469804729885.tap'
```

These accumulate because internet access of that app is firewalled. 
It's a known issue with the crashlytics library (and others).
For this reason the "Analytics filter" was added to the AppCleaner.
If you let SD Maid finish and the filter was activated, then you should be able to delete them all.

**Comment by dieselzackab** [comment]
oh ok I appreciate your help!!
