### ISSUE TITLE
Available on F-Droid?

### ISSUE THREAD

**Issue by JonnyTech** [d4rken/sdmaid-public#777]
Can you please make SDMaid available on [F-Droid](http://f-droid.org/)?

**Comment by d4rken** [comment]
SD Maid is not open source.

**Comment by JonnyTech** [comment]
Ah, my bad, assumed it was since on github, I must check before posting...

**Comment by d4rken** [comment]
I've thought many times about open sourcing SD Maid.

I would enjoy for my code to be reviewed and nitpicked (so I can improve my coding skills), but in my experience contributions are usually a lot less than what you would expect, such that a projects usually only move forward due to a handful of maintainers and not dozen of random contributors.

Other projects have also shown me that people will just take the code (app) and reupload it with a different name. While this may be allowed depending on license, it's a dick move and not what open source is for (in my opinion). Even if it's not allowed, combating such actions would also suck the fun out of ones day.

This in turn would kill my motiviation and cause SD Maids development to grind to a halt as I doubt random contributions would match the amount of development that would cease from my side.

So in the bigger picture, open sourcing SD Maid would likely be bad for SD Maids future development.

I'm thinking about open sourcing a few sub components though as I think it will improve the overall state of Android developement in that area as there is knowing comparable available. E.g. Modules related to using root or accessing storage.

**Comment by JonnyTech** [comment]
I am with you on all of those points that you have raised. It is a shame really that the potential of open source is never fully realised and often abused. Well done though for thinking of the bigger picture and I hope that those components serve others well.

**Comment by samantohermes** [comment]
But at least you can make a custom repository. Some of them contain proprietary apps:
https://forum.f-droid.org/t/known-repositories/721
