### ISSUE TITLE
Remember AppControl filter settings

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#926]
AppControl: I would like to preset Sort mode and Categories.
Please add this options in Setting of AppControl.

**Comment by juniorasher** [comment]
Ya

**Comment by d4rken** [comment]
The sortmode is already remembered, it's always the last one that was selected.

Can you describe your usecase for this feature?

**Comment by Ya8Sa** [comment]
Sort mode may be OK.
Categories is back to All items after scanning, I like to keep others, such as Running.
Thanks.

**Comment by d4rken** [comment]
The default setting is to show all apps, isn't that what you would like to see first before filtering out items?

**Comment by Ya8Sa** [comment]
No, I would like to keep previous filtered item such as "Runnning", it is similar to Sort mode.
Current behavior reset to All items when restarting app after exit, changing other tab then returning to AppControl. In any cases I prefer showing previous same categories.
Additionally, some items can be selected at once, however it shows zero item due to AND operation, it should be OR operation.

**Comment by d4rken** [comment]
> Additionally, some items can be selected at once, however it shows zero item due to AND operation, it should be OR operation.

Should it though? What if you only want to show frozen system apps, now you can just select "frozen" + "system".

**Comment by Ya8Sa** [comment]
Understood and reconsiderd.  And cancel this request.

**Comment by d4rken** [comment]
I'll look into making sure the filter settings are remembered when switching pages, until SD Maid is closed.

**Comment by d4rken** [comment]
Dup of #1558
